/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/components/index';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from 'ng2-validation/dist/directives';
import * as import6 from 'ng2-slim-loading-bar/index';
import * as import7 from '@angular/common/src/common_module';
import * as import8 from 'angular2-moment/moment.module';
import * as import9 from 'ng2-toasty/index';
import * as import10 from 'angular2-material-datepicker/src/datepicker.module';
import * as import11 from 'primeng/components/button/button';
import * as import12 from 'primeng/components/inputtext/inputtext';
import * as import13 from 'primeng/components/calendar/calendar';
import * as import14 from 'angular2-infinite-scroll/src/index';
import * as import15 from '../../../../src/app/shared/index';
import * as import16 from '../../../../src/app/components/dashboard/index';
import * as import17 from '../../../../src/app/components/search/index';
import * as import18 from '@angular/core/src/application_module';
import * as import19 from '@angular/platform-browser/src/browser';
import * as import20 from '../../../../src/app/components/user/index';
import * as import21 from '../../../../src/app/components/trips/index';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/forms/src/form_builder';
import * as import24 from 'ng2-slim-loading-bar/src/slim-loading-bar.service';
import * as import25 from '@angular/common/src/localization';
import * as import26 from 'ng2-toasty/src/toasty.service';
import * as import27 from 'angular2-infinite-scroll/src/axis-resolver';
import * as import28 from 'angular2-infinite-scroll/src/position-resolver';
import * as import29 from '@angular/core/src/application_init';
import * as import30 from '@angular/core/src/testability/testability';
import * as import31 from '@angular/core/src/application_ref';
import * as import32 from '@angular/core/src/linker/compiler';
import * as import33 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import34 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import35 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import36 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import37 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import38 from '@angular/core/src/animation/animation_queue';
import * as import39 from '@angular/core/src/linker/view_utils';
import * as import40 from '@angular/platform-browser/src/browser/title';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from './dashboard/dashboard.component.ngfactory';
import * as import43 from './dashboard/feed-trips/feed-trips.component.ngfactory';
import * as import44 from './dashboard/trending-trips/trending-trips.component.ngfactory';
import * as import45 from './search/search.component.ngfactory';
import * as import46 from './user/user.component.ngfactory';
import * as import47 from './user/user-settings/user-settings.component.ngfactory';
import * as import48 from './user/user-profile/user-profile.component.ngfactory';
import * as import49 from './user/user-profile/user-trips/user-trips.component.ngfactory';
import * as import50 from './user/user-profile/user-media/user-media.component.ngfactory';
import * as import51 from './user/user-profile/user-followers/user-followers.component.ngfactory';
import * as import52 from './user/user-profile/user-following/user-following.component.ngfactory';
import * as import53 from './trips/trips.component.ngfactory';
import * as import54 from './trips/trip-edit/trip-edit.component.ngfactory';
import * as import55 from './trips/trip-detail/trip-detail.component.ngfactory';
import * as import56 from '@angular/core/src/i18n/tokens';
import * as import57 from '../../../../src/app/components/dashboard/dashboard.component';
import * as import58 from '../../../../src/app/components/dashboard/feed-trips/feed-trips.component';
import * as import59 from '../../../../src/app/components/dashboard/trending-trips/trending-trips.component';
import * as import60 from '../../../../src/app/components/search/search.component';
import * as import61 from '../../../../src/app/components/user/user.component';
import * as import62 from '../../../../src/app/components/user/user-settings/user-settings.component';
import * as import63 from '../../../../src/app/components/user/user-profile/user-profile.component';
import * as import64 from '../../../../src/app/components/user/user-profile/user-trips/user-trips.component';
import * as import65 from '../../../../src/app/components/user/user-profile/user-media/user-media.component';
import * as import66 from '../../../../src/app/components/user/user-profile/user-followers/user-followers.component';
import * as import67 from '../../../../src/app/components/user/user-profile/user-following/user-following.component';
import * as import68 from '../../../../src/app/components/trips/trips.component';
import * as import69 from '../../../../src/app/components/trips/trip-edit/trip-edit.component';
import * as import70 from '../../../../src/app/guards/auth.guard';
import * as import71 from '../../../../src/app/components/trips/trip-detail/trip-detail.component';
import * as import72 from '../../../../src/app/guards/trips-resolve.guard';
import * as import73 from '@angular/core/src/application_tokens';
import * as import74 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import75 from '@angular/platform-browser/src/dom/events/key_events';
import * as import76 from '@angular/core/src/zone/ng_zone';
import * as import77 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import78 from '@angular/core/src/console';
import * as import79 from '@angular/router/src/router_config_loader';
import * as import80 from '@angular/core/src/error_handler';
import * as import81 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import82 from '@angular/platform-browser/src/dom/animation_driver';
import * as import83 from '@angular/core/src/render/api';
import * as import84 from '@angular/core/src/security';
import * as import85 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import86 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class ComponentsModuleInjector extends import0.NgModuleInjector<import1.ComponentsModule> {
  _RouterModule_0:import2.RouterModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _CustomFormsModule_3:import5.CustomFormsModule;
  _ReactiveFormsModule_4:import4.ReactiveFormsModule;
  _SlimLoadingBarModule_5:import6.SlimLoadingBarModule;
  _CommonModule_6:import7.CommonModule;
  _MomentModule_7:import8.MomentModule;
  _ToastyModule_8:import9.ToastyModule;
  _DatepickerModule_9:import10.DatepickerModule;
  _ButtonModule_10:import11.ButtonModule;
  _InputTextModule_11:import12.InputTextModule;
  _CalendarModule_12:import13.CalendarModule;
  _InfiniteScrollModule_13:import14.InfiniteScrollModule;
  _SharedModule_14:import15.SharedModule;
  _DashboardModule_15:import16.DashboardModule;
  _SearchModule_16:import17.SearchModule;
  _ApplicationModule_17:import18.ApplicationModule;
  _BrowserModule_18:import19.BrowserModule;
  _UserModule_19:import20.UserModule;
  _TripsModule_20:import21.TripsModule;
  _ComponentsModule_21:import1.ComponentsModule;
  __RadioControlRegistry_22:import22.RadioControlRegistry;
  __FormBuilder_23:import23.FormBuilder;
  __SlimLoadingBarService_24:import24.SlimLoadingBarService;
  __LOCALE_ID_25:any;
  __NgLocalization_26:import25.NgLocaleLocalization;
  __ToastyConfig_27:import26.ToastyConfig;
  __ToastyService_28:any;
  __AxisResolverFactory_29:import27.AxisResolverFactory;
  __PositionResolverFactory_30:import28.PositionResolverFactory;
  __ROUTES_31:any[];
  _ErrorHandler_32:any;
  _ApplicationInitStatus_33:import29.ApplicationInitStatus;
  _Testability_34:import30.Testability;
  _ApplicationRef__35:import31.ApplicationRef_;
  __ApplicationRef_36:any;
  __Compiler_37:import32.Compiler;
  __APP_ID_38:any;
  __DOCUMENT_39:any;
  __HAMMER_GESTURE_CONFIG_40:import33.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_41:any[];
  __EventManager_42:import34.EventManager;
  __DomSharedStylesHost_43:import35.DomSharedStylesHost;
  __AnimationDriver_44:any;
  __DomRootRenderer_45:import36.DomRootRenderer_;
  __RootRenderer_46:any;
  __DomSanitizer_47:import37.DomSanitizerImpl;
  __Sanitizer_48:any;
  __AnimationQueue_49:import38.AnimationQueue;
  __ViewUtils_50:import39.ViewUtils;
  __IterableDiffers_51:any;
  __KeyValueDiffers_52:any;
  __SharedStylesHost_53:any;
  __Title_54:import40.Title;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.DashboardComponentNgFactory,
      import43.FeedTripsComponentNgFactory,
      import44.TrendingTripsComponentNgFactory,
      import45.SearchComponentNgFactory,
      import46.UserComponentNgFactory,
      import47.UserSettingsComponentNgFactory,
      import48.UserProfileComponentNgFactory,
      import49.UserTripsComponentNgFactory,
      import50.UserMediaComponentNgFactory,
      import51.UserFollowersComponentNgFactory,
      import52.UserFollowingComponentNgFactory,
      import53.TripsComponentNgFactory,
      import54.TripEditComponentNgFactory,
      import55.TripDetailComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _RadioControlRegistry_22():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_22 == null)) { (this.__RadioControlRegistry_22 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_22;
  }
  get _FormBuilder_23():import23.FormBuilder {
    if ((this.__FormBuilder_23 == null)) { (this.__FormBuilder_23 = new import23.FormBuilder()); }
    return this.__FormBuilder_23;
  }
  get _SlimLoadingBarService_24():import24.SlimLoadingBarService {
    if ((this.__SlimLoadingBarService_24 == null)) { (this.__SlimLoadingBarService_24 = new import24.SlimLoadingBarService()); }
    return this.__SlimLoadingBarService_24;
  }
  get _LOCALE_ID_25():any {
    if ((this.__LOCALE_ID_25 == null)) { (this.__LOCALE_ID_25 = import18._localeFactory(this.parent.get(import56.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_25;
  }
  get _NgLocalization_26():import25.NgLocaleLocalization {
    if ((this.__NgLocalization_26 == null)) { (this.__NgLocalization_26 = new import25.NgLocaleLocalization(this._LOCALE_ID_25)); }
    return this.__NgLocalization_26;
  }
  get _ToastyConfig_27():import26.ToastyConfig {
    if ((this.__ToastyConfig_27 == null)) { (this.__ToastyConfig_27 = new import26.ToastyConfig()); }
    return this.__ToastyConfig_27;
  }
  get _ToastyService_28():any {
    if ((this.__ToastyService_28 == null)) { (this.__ToastyService_28 = import26.toastyServiceFactory(this._ToastyConfig_27)); }
    return this.__ToastyService_28;
  }
  get _AxisResolverFactory_29():import27.AxisResolverFactory {
    if ((this.__AxisResolverFactory_29 == null)) { (this.__AxisResolverFactory_29 = new import27.AxisResolverFactory()); }
    return this.__AxisResolverFactory_29;
  }
  get _PositionResolverFactory_30():import28.PositionResolverFactory {
    if ((this.__PositionResolverFactory_30 == null)) { (this.__PositionResolverFactory_30 = new import28.PositionResolverFactory(this._AxisResolverFactory_29)); }
    return this.__PositionResolverFactory_30;
  }
  get _ROUTES_31():any[] {
    if ((this.__ROUTES_31 == null)) { (this.__ROUTES_31 = [
      ([] as any[]),
        [{
          path: 'dashboard',
          component: import57.DashboardComponent,
          children: [
            {
              path: '',
              redirectTo: 'feeds',
              pathMatch: 'full'
            }
            ,
            {
              path: 'feeds',
              component: import58.FeedTripsComponent
            }
            ,
            {
              path: 'trending',
              component: import59.TrendingTripsComponent
            }

          ]

        }
      ],
        [{
          path: 'search',
          component: import60.SearchComponent
        }
      ],
        [{
          path: 'user',
          component: import61.UserComponent,
          children: [
            {
              path: 'settings',
              component: import62.UserSettingsComponent
            }
            ,
            {
              path: ':id',
              component: import63.UserProfileComponent,
              children: [
                {
                  path: '',
                  redirectTo: 'trips',
                  pathMatch: 'full'
                }
                ,
                {
                  path: 'trips',
                  component: import64.UserTripsComponent
                }
                ,
                {
                  path: 'media',
                  component: import65.UserMediaComponent
                }
                ,
                {
                  path: 'followers',
                  component: import66.UserFollowersComponent
                }
                ,
                {
                  path: 'following',
                  component: import67.UserFollowingComponent
                }

              ]

            }

          ]

        }
      ],
        [{
          path: 'trips',
          component: import68.TripsComponent,
          children: [
            {
              path: 'new',
              component: import69.TripEditComponent,
              canActivate: [import70.CanActivateViaAuthGuard]
            }
            ,
            {
              path: ':id',
              component: import71.TripDetailComponent,
              resolve: {trip: import72.TripsResolveGuard}
            }
            ,
            {
              path: ':id/edit',
              component: import69.TripEditComponent,
              resolve: {trip: import72.TripsResolveGuard},
              canActivate: [import70.CanActivateViaAuthGuard]
            }

          ]

        }
      ]
    ]
    ); }
    return this.__ROUTES_31;
  }
  get _ApplicationRef_36():any {
    if ((this.__ApplicationRef_36 == null)) { (this.__ApplicationRef_36 = this._ApplicationRef__35); }
    return this.__ApplicationRef_36;
  }
  get _Compiler_37():import32.Compiler {
    if ((this.__Compiler_37 == null)) { (this.__Compiler_37 = new import32.Compiler()); }
    return this.__Compiler_37;
  }
  get _APP_ID_38():any {
    if ((this.__APP_ID_38 == null)) { (this.__APP_ID_38 = import73._appIdRandomProviderFactory()); }
    return this.__APP_ID_38;
  }
  get _DOCUMENT_39():any {
    if ((this.__DOCUMENT_39 == null)) { (this.__DOCUMENT_39 = import19._document()); }
    return this.__DOCUMENT_39;
  }
  get _HAMMER_GESTURE_CONFIG_40():import33.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_40 == null)) { (this.__HAMMER_GESTURE_CONFIG_40 = new import33.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_40;
  }
  get _EVENT_MANAGER_PLUGINS_41():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_41 == null)) { (this.__EVENT_MANAGER_PLUGINS_41 = [
      new import74.DomEventsPlugin(),
      new import75.KeyEventsPlugin(),
      new import33.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_40)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_41;
  }
  get _EventManager_42():import34.EventManager {
    if ((this.__EventManager_42 == null)) { (this.__EventManager_42 = new import34.EventManager(this._EVENT_MANAGER_PLUGINS_41,this.parent.get(import76.NgZone))); }
    return this.__EventManager_42;
  }
  get _DomSharedStylesHost_43():import35.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_43 == null)) { (this.__DomSharedStylesHost_43 = new import35.DomSharedStylesHost(this._DOCUMENT_39)); }
    return this.__DomSharedStylesHost_43;
  }
  get _AnimationDriver_44():any {
    if ((this.__AnimationDriver_44 == null)) { (this.__AnimationDriver_44 = import19._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_44;
  }
  get _DomRootRenderer_45():import36.DomRootRenderer_ {
    if ((this.__DomRootRenderer_45 == null)) { (this.__DomRootRenderer_45 = new import36.DomRootRenderer_(this._DOCUMENT_39,this._EventManager_42,this._DomSharedStylesHost_43,this._AnimationDriver_44,this._APP_ID_38)); }
    return this.__DomRootRenderer_45;
  }
  get _RootRenderer_46():any {
    if ((this.__RootRenderer_46 == null)) { (this.__RootRenderer_46 = import77._createConditionalRootRenderer(this._DomRootRenderer_45,this.parent.get(import77.NgProbeToken,(null as any)),this.parent.get(import31.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_46;
  }
  get _DomSanitizer_47():import37.DomSanitizerImpl {
    if ((this.__DomSanitizer_47 == null)) { (this.__DomSanitizer_47 = new import37.DomSanitizerImpl()); }
    return this.__DomSanitizer_47;
  }
  get _Sanitizer_48():any {
    if ((this.__Sanitizer_48 == null)) { (this.__Sanitizer_48 = this._DomSanitizer_47); }
    return this.__Sanitizer_48;
  }
  get _AnimationQueue_49():import38.AnimationQueue {
    if ((this.__AnimationQueue_49 == null)) { (this.__AnimationQueue_49 = new import38.AnimationQueue(this.parent.get(import76.NgZone))); }
    return this.__AnimationQueue_49;
  }
  get _ViewUtils_50():import39.ViewUtils {
    if ((this.__ViewUtils_50 == null)) { (this.__ViewUtils_50 = new import39.ViewUtils(this._RootRenderer_46,this._Sanitizer_48,this._AnimationQueue_49)); }
    return this.__ViewUtils_50;
  }
  get _IterableDiffers_51():any {
    if ((this.__IterableDiffers_51 == null)) { (this.__IterableDiffers_51 = import18._iterableDiffersFactory()); }
    return this.__IterableDiffers_51;
  }
  get _KeyValueDiffers_52():any {
    if ((this.__KeyValueDiffers_52 == null)) { (this.__KeyValueDiffers_52 = import18._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_52;
  }
  get _SharedStylesHost_53():any {
    if ((this.__SharedStylesHost_53 == null)) { (this.__SharedStylesHost_53 = this._DomSharedStylesHost_43); }
    return this.__SharedStylesHost_53;
  }
  get _Title_54():import40.Title {
    if ((this.__Title_54 == null)) { (this.__Title_54 = new import40.Title()); }
    return this.__Title_54;
  }
  createInternal():import1.ComponentsModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._CustomFormsModule_3 = new import5.CustomFormsModule();
    this._ReactiveFormsModule_4 = new import4.ReactiveFormsModule();
    this._SlimLoadingBarModule_5 = new import6.SlimLoadingBarModule();
    this._CommonModule_6 = new import7.CommonModule();
    this._MomentModule_7 = new import8.MomentModule();
    this._ToastyModule_8 = new import9.ToastyModule();
    this._DatepickerModule_9 = new import10.DatepickerModule();
    this._ButtonModule_10 = new import11.ButtonModule();
    this._InputTextModule_11 = new import12.InputTextModule();
    this._CalendarModule_12 = new import13.CalendarModule();
    this._InfiniteScrollModule_13 = new import14.InfiniteScrollModule();
    this._SharedModule_14 = new import15.SharedModule();
    this._DashboardModule_15 = new import16.DashboardModule();
    this._SearchModule_16 = new import17.SearchModule();
    this._ApplicationModule_17 = new import18.ApplicationModule();
    this._BrowserModule_18 = new import19.BrowserModule(this.parent.get(import19.BrowserModule,(null as any)));
    this._UserModule_19 = new import20.UserModule();
    this._TripsModule_20 = new import21.TripsModule();
    this._ComponentsModule_21 = new import1.ComponentsModule();
    this._ErrorHandler_32 = import19.errorHandler();
    this._ApplicationInitStatus_33 = new import29.ApplicationInitStatus(this.parent.get(import29.APP_INITIALIZER,(null as any)));
    this._Testability_34 = new import30.Testability(this.parent.get(import76.NgZone));
    this._ApplicationRef__35 = new import31.ApplicationRef_(this.parent.get(import76.NgZone),this.parent.get(import78.Console),this,this._ErrorHandler_32,this,this._ApplicationInitStatus_33,this.parent.get(import30.TestabilityRegistry,(null as any)),this._Testability_34);
    return this._ComponentsModule_21;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.CustomFormsModule)) { return this._CustomFormsModule_3; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.SlimLoadingBarModule)) { return this._SlimLoadingBarModule_5; }
    if ((token === import7.CommonModule)) { return this._CommonModule_6; }
    if ((token === import8.MomentModule)) { return this._MomentModule_7; }
    if ((token === import9.ToastyModule)) { return this._ToastyModule_8; }
    if ((token === import10.DatepickerModule)) { return this._DatepickerModule_9; }
    if ((token === import11.ButtonModule)) { return this._ButtonModule_10; }
    if ((token === import12.InputTextModule)) { return this._InputTextModule_11; }
    if ((token === import13.CalendarModule)) { return this._CalendarModule_12; }
    if ((token === import14.InfiniteScrollModule)) { return this._InfiniteScrollModule_13; }
    if ((token === import15.SharedModule)) { return this._SharedModule_14; }
    if ((token === import16.DashboardModule)) { return this._DashboardModule_15; }
    if ((token === import17.SearchModule)) { return this._SearchModule_16; }
    if ((token === import18.ApplicationModule)) { return this._ApplicationModule_17; }
    if ((token === import19.BrowserModule)) { return this._BrowserModule_18; }
    if ((token === import20.UserModule)) { return this._UserModule_19; }
    if ((token === import21.TripsModule)) { return this._TripsModule_20; }
    if ((token === import1.ComponentsModule)) { return this._ComponentsModule_21; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_22; }
    if ((token === import23.FormBuilder)) { return this._FormBuilder_23; }
    if ((token === import24.SlimLoadingBarService)) { return this._SlimLoadingBarService_24; }
    if ((token === import56.LOCALE_ID)) { return this._LOCALE_ID_25; }
    if ((token === import25.NgLocalization)) { return this._NgLocalization_26; }
    if ((token === import26.ToastyConfig)) { return this._ToastyConfig_27; }
    if ((token === import26.ToastyService)) { return this._ToastyService_28; }
    if ((token === import27.AxisResolverFactory)) { return this._AxisResolverFactory_29; }
    if ((token === import28.PositionResolverFactory)) { return this._PositionResolverFactory_30; }
    if ((token === import79.ROUTES)) { return this._ROUTES_31; }
    if ((token === import80.ErrorHandler)) { return this._ErrorHandler_32; }
    if ((token === import29.ApplicationInitStatus)) { return this._ApplicationInitStatus_33; }
    if ((token === import30.Testability)) { return this._Testability_34; }
    if ((token === import31.ApplicationRef_)) { return this._ApplicationRef__35; }
    if ((token === import31.ApplicationRef)) { return this._ApplicationRef_36; }
    if ((token === import32.Compiler)) { return this._Compiler_37; }
    if ((token === import73.APP_ID)) { return this._APP_ID_38; }
    if ((token === import81.DOCUMENT)) { return this._DOCUMENT_39; }
    if ((token === import33.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_40; }
    if ((token === import34.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_41; }
    if ((token === import34.EventManager)) { return this._EventManager_42; }
    if ((token === import35.DomSharedStylesHost)) { return this._DomSharedStylesHost_43; }
    if ((token === import82.AnimationDriver)) { return this._AnimationDriver_44; }
    if ((token === import36.DomRootRenderer)) { return this._DomRootRenderer_45; }
    if ((token === import83.RootRenderer)) { return this._RootRenderer_46; }
    if ((token === import37.DomSanitizer)) { return this._DomSanitizer_47; }
    if ((token === import84.Sanitizer)) { return this._Sanitizer_48; }
    if ((token === import38.AnimationQueue)) { return this._AnimationQueue_49; }
    if ((token === import39.ViewUtils)) { return this._ViewUtils_50; }
    if ((token === import85.IterableDiffers)) { return this._IterableDiffers_51; }
    if ((token === import86.KeyValueDiffers)) { return this._KeyValueDiffers_52; }
    if ((token === import35.SharedStylesHost)) { return this._SharedStylesHost_53; }
    if ((token === import40.Title)) { return this._Title_54; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__35.ngOnDestroy();
  }
}
export const ComponentsModuleNgFactory:import0.NgModuleFactory<import1.ComponentsModule> = new import0.NgModuleFactory(ComponentsModuleInjector,import1.ComponentsModule);