/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.banner-image[_ngcontent-%COMP%] {\n    margin: 0 auto;\n    text-align: center;\n}\n\n.join-form[_ngcontent-%COMP%] {\n    margin-top: 40px;\n}\n\n.campain-text[_ngcontent-%COMP%] {\n    width: 70rem;\n    font-size: 2rem;\n    margin: 30px auto 0px auto;\n    line-height: 2.4rem;\n}'];