/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../src/app/components/user/user-settings/change-password/change-password.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../../../src/app/services/user.service';
import * as import9 from './change-password.component.scss.shim.ngstyle';
import * as import10 from '../../../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '../../../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import13 from '../../../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import14 from '../../../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import15 from '@angular/core/src/change_detection/change_detection_util';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_model';
import * as import20 from '@angular/forms/src/directives/ng_control';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from '@angular/forms/src/directives/validators';
import * as import23 from '@angular/forms/src/validators';
import * as import24 from '@angular/forms/src/directives/ng_form';
import * as import25 from '@angular/forms/src/directives/control_container';
export class Wrapper_ChangePasswordComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ChangePasswordComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.ChangePasswordComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ChangePasswordComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ChangePasswordComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ChangePasswordComponent>;
  _ChangePasswordComponent_0_3:Wrapper_ChangePasswordComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChangePasswordComponent_Host0,renderType_ChangePasswordComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-change-password',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ChangePasswordComponent0(this.viewUtils,this,0,this._el_0);
    this._ChangePasswordComponent_0_3 = new Wrapper_ChangePasswordComponent(this.injectorGet(import8.UserService,this.parentIndex));
    this.compView_0.create(this._ChangePasswordComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ChangePasswordComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ChangePasswordComponent) && (0 === requestNodeIndex))) { return this._ChangePasswordComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ChangePasswordComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ChangePasswordComponentNgFactory:import7.ComponentFactory<import0.ChangePasswordComponent> = new import7.ComponentFactory<import0.ChangePasswordComponent>('tr-change-password',View_ChangePasswordComponent_Host0,import0.ChangePasswordComponent);
const styles_ChangePasswordComponent:any[] = [import9.styles];
var renderType_ChangePasswordComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ChangePasswordComponent,{});
export class View_ChangePasswordComponent0 extends import1.AppView<import0.ChangePasswordComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgForm_14_3:import10.Wrapper_NgForm;
  _ControlContainer_14_4:any;
  _NgControlStatusGroup_14_5:import11.Wrapper_NgControlStatusGroup;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_23_4:any[];
  _NgModel_23_5:import13.Wrapper_NgModel;
  _NgControl_23_6:any;
  _NgControlStatus_23_7:import11.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import12.Wrapper_DefaultValueAccessor;
  _RequiredValidator_31_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_31_5:any[];
  _NG_VALUE_ACCESSOR_31_6:any[];
  _NgModel_31_7:import13.Wrapper_NgModel;
  _NgControl_31_8:any;
  _NgControlStatus_31_9:import11.Wrapper_NgControlStatus;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _DefaultValueAccessor_43_3:import12.Wrapper_DefaultValueAccessor;
  _RequiredValidator_43_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_43_5:any[];
  _NG_VALUE_ACCESSOR_43_6:any[];
  _NgModel_43_7:import13.Wrapper_NgModel;
  _NgControl_43_8:any;
  _NgControlStatus_43_9:import11.Wrapper_NgControlStatus;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  /*private*/ _expr_84:any;
  /*private*/ _expr_85:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChangePasswordComponent0,renderType_ChangePasswordComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_84 = import15.UNINITIALIZED;
    this._expr_85 = import15.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','ui middle aligned center aligned grid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','sixteen wide column'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','sixteen wide column'),(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','five wide column'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h2',new import3.InlineArray2(2,'class','ui teal image header'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        Change Password\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'form',new import3.InlineArray4(4,'class','ui medium form','novalidate',''),(null as any));
    this._NgForm_14_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_14_4 = this._NgForm_14_3.context;
    this._NgControlStatusGroup_14_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_14_4);
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','ui stacked segment'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','form-group field'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',new import3.InlineArray2(2,'for',''),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Old Password',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray8(6,'class','form-control','name','oldPassword','type','password'),(null as any));
    this._DefaultValueAccessor_23_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_23));
    this._NG_VALUE_ACCESSOR_23_4 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_5 = new import13.Wrapper_NgModel(this._ControlContainer_14_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_23_4);
    this._NgControl_23_6 = this._NgModel_23_5.context;
    this._NgControlStatus_23_7 = new import11.Wrapper_NgControlStatus(this._NgControl_23_6);
    this._text_24 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n\n          ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','form-group field'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'label',new import3.InlineArray2(2,'for',''),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'New Password',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_26,'input',new import3.InlineArray16(12,'class','form-control','name','password','required','','reverse','true','type','password','validateEqual','confirmPassword'),(null as any));
    this._DefaultValueAccessor_31_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_31));
    this._RequiredValidator_31_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_31_5 = [this._RequiredValidator_31_4.context];
    this._NG_VALUE_ACCESSOR_31_6 = [this._DefaultValueAccessor_31_3.context];
    this._NgModel_31_7 = new import13.Wrapper_NgModel(this._ControlContainer_14_4,this._NG_VALIDATORS_31_5,(null as any),this._NG_VALUE_ACCESSOR_31_6);
    this._NgControl_31_8 = this._NgModel_31_7.context;
    this._NgControlStatus_31_9 = new import11.Wrapper_NgControlStatus(this._NgControl_31_8);
    this._text_32 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_26,'small',new import3.InlineArray2(2,'class','text-danger'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n              Password is required\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._text_37 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','form-group field'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'label',new import3.InlineArray2(2,'for',''),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Retype password',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_38,'input',new import3.InlineArray16(12,'class','form-control','name','confirmPassword','required','','reverse','false','type','password','validateEqual','password'),(null as any));
    this._DefaultValueAccessor_43_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_43));
    this._RequiredValidator_43_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_43_5 = [this._RequiredValidator_43_4.context];
    this._NG_VALUE_ACCESSOR_43_6 = [this._DefaultValueAccessor_43_3.context];
    this._NgModel_43_7 = new import13.Wrapper_NgModel(this._ControlContainer_14_4,this._NG_VALIDATORS_43_5,(null as any),this._NG_VALUE_ACCESSOR_43_6);
    this._NgControl_43_8 = this._NgModel_43_7.context;
    this._NgControlStatus_43_9 = new import11.Wrapper_NgControlStatus(this._NgControl_43_8);
    this._text_44 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_38,'small',new import3.InlineArray2(2,'class','text-danger'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n              Password mismatch\n            ',(null as any));
    this._text_47 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._text_49 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','field'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n            ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'button',new import3.InlineArray4(4,'class','ui fluid large teal submit button','type','submit'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Change Password',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n          ',(null as any));
    this._text_55 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._text_57 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','ui message'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'\n      Have a Nice Day!!! \n    ',(null as any));
    this._text_60 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_61 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_14));
    this._NgForm_14_3.subscribe(this,this.eventHandler(this.handleEvent_14),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_5.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_31));
    this._NgModel_31_7.subscribe(this,this.eventHandler(this.handleEvent_31),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_43,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_43));
    this._NgModel_43_7.subscribe(this,this.eventHandler(this.handleEvent_43),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_4; }
    if (((token === import19.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_5.context; }
    if (((token === import20.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_6; }
    if (((token === import21.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_7.context; }
    if (((token === import17.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3.context; }
    if (((token === import22.RequiredValidator) && (31 === requestNodeIndex))) { return this._RequiredValidator_31_4.context; }
    if (((token === import23.NG_VALIDATORS) && (31 === requestNodeIndex))) { return this._NG_VALIDATORS_31_5; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_6; }
    if (((token === import19.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_7.context; }
    if (((token === import20.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_8; }
    if (((token === import21.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_9.context; }
    if (((token === import17.DefaultValueAccessor) && (43 === requestNodeIndex))) { return this._DefaultValueAccessor_43_3.context; }
    if (((token === import22.RequiredValidator) && (43 === requestNodeIndex))) { return this._RequiredValidator_43_4.context; }
    if (((token === import23.NG_VALIDATORS) && (43 === requestNodeIndex))) { return this._NG_VALIDATORS_43_5; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_6; }
    if (((token === import19.NgModel) && (43 === requestNodeIndex))) { return this._NgModel_43_7.context; }
    if (((token === import20.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_8; }
    if (((token === import21.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_9.context; }
    if (((token === import24.NgForm) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgForm_14_3.context; }
    if (((token === import25.ControlContainer) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ControlContainer_14_4; }
    if (((token === import21.NgControlStatusGroup) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgControlStatusGroup_14_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this._NgControlStatusGroup_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = 'oldPassword';
    this._NgModel_23_5.check_name(currVal_23_1_0,throwOnChange,false);
    const currVal_23_1_1:any = this.context.oldPassword;
    this._NgModel_23_5.check_model(currVal_23_1_1,throwOnChange,false);
    this._NgModel_23_5.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._DefaultValueAccessor_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_1_0:any = '';
    this._RequiredValidator_31_4.check_required(currVal_31_1_0,throwOnChange,false);
    this._RequiredValidator_31_4.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_2_0:any = 'password';
    this._NgModel_31_7.check_name(currVal_31_2_0,throwOnChange,false);
    const currVal_31_2_1:any = this.context.password;
    this._NgModel_31_7.check_model(currVal_31_2_1,throwOnChange,false);
    this._NgModel_31_7.ngDoCheck(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.ngDoCheck(this,this._el_31,throwOnChange);
    this._DefaultValueAccessor_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_1_0:any = '';
    this._RequiredValidator_43_4.check_required(currVal_43_1_0,throwOnChange,false);
    this._RequiredValidator_43_4.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_2_0:any = 'confirmPassword';
    this._NgModel_43_7.check_name(currVal_43_2_0,throwOnChange,false);
    const currVal_43_2_1:any = this.context.confirmPassword;
    this._NgModel_43_7.check_model(currVal_43_2_1,throwOnChange,false);
    this._NgModel_43_7.ngDoCheck(this,this._el_43,throwOnChange);
    this._NgControlStatus_43_9.ngDoCheck(this,this._el_43,throwOnChange);
    this._NgControlStatusGroup_14_5.checkHost(this,this,this._el_14,throwOnChange);
    this._NgControlStatus_23_7.checkHost(this,this,this._el_23,throwOnChange);
    this._RequiredValidator_31_4.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.checkHost(this,this,this._el_31,throwOnChange);
    const currVal_84:any = (this._NgModel_31_7.context.valid || (this._NgModel_31_7.context.pristine && !this._NgForm_14_3.context.submitted));
    if (import3.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setElementProperty(this._el_33,'hidden',currVal_84);
      this._expr_84 = currVal_84;
    }
    this._RequiredValidator_43_4.checkHost(this,this,this._el_43,throwOnChange);
    this._NgControlStatus_43_9.checkHost(this,this,this._el_43,throwOnChange);
    const currVal_85:any = (this._NgModel_43_7.context.valid || (this._NgModel_43_7.context.pristine && !this._NgForm_14_3.context.submitted));
    if (import3.checkBinding(throwOnChange,this._expr_85,currVal_85)) {
      this.renderer.setElementProperty(this._el_45,'hidden',currVal_85);
      this._expr_85 = currVal_85;
    }
  }
  destroyInternal():void {
    this._NgModel_23_5.ngOnDestroy();
    this._NgModel_31_7.ngOnDestroy();
    this._NgModel_43_7.ngOnDestroy();
    this._NgForm_14_3.ngOnDestroy();
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.changePassword(this._NgForm_14_3.context.valid)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.oldPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_31_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_43(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_43_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.confirmPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}