/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.ui.image[_ngcontent-%COMP%] {\n  cursor: pointer;\n}\n\n.header[_ngcontent-%COMP%] {\n  cursor: pointer;\n}'];