/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.search-box-cover[_ngcontent-%COMP%] {\n	width: 100%;\n	margin-top: -1%;\n	border: none;\n}\n\n.search-box-cover-div[_ngcontent-%COMP%] {\n	position: relative;\n	height: 17rem;\n	overflow: hidden;\n	&:hover {\n		.cover-update-text {\n			opacity: 1;\n		}\n	}\n}\n\n.cover-image[_ngcontent-%COMP%] {\n	width: 100%;	\n}\n\n.search-box[_ngcontent-%COMP%] {\n  position: absolute;\n	transform: translateZ;\n	top: 25%;\n	left: 50%;\n	transform: translate(-50%);\n	z-index: 1;\n  padding: 2.5%;\n  border-radius: 5px;\n  min-width: 400px;\n  width: 70%;\n  h1, h2{\n    font-weight: 100;\n    text-shadow: 1px 1px 8px #111;\n  }\n}'];