/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/components/dashboard/dashboard.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './dashboard.component.scss.shim.ngstyle';
import * as import9 from '../../../../../src/app/components/dashboard/dashboard-search/dashboard-search.component';
import * as import10 from './dashboard-search/dashboard-search.component.ngfactory';
import * as import11 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '../../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../../../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import16 from '@ngrx/store/src/store';
import * as import17 from '@angular/router/src/router';
import * as import18 from '@angular/router/src/router_state';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/router/src/router_outlet_map';
import * as import21 from '@angular/core/src/linker/component_factory_resolver';
import * as import22 from '@angular/router/src/directives/router_link';
import * as import23 from '@angular/router/src/directives/router_link_active';
import * as import24 from '@angular/router/src/directives/router_outlet';
export class Wrapper_DashboardComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DashboardComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.DashboardComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_DashboardComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_DashboardComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.DashboardComponent>;
  _DashboardComponent_0_3:Wrapper_DashboardComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardComponent_Host0,renderType_DashboardComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-dashboard',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DashboardComponent0(this.viewUtils,this,0,this._el_0);
    this._DashboardComponent_0_3 = new Wrapper_DashboardComponent();
    this.compView_0.create(this._DashboardComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._DashboardComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DashboardComponent) && (0 === requestNodeIndex))) { return this._DashboardComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DashboardComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DashboardComponentNgFactory:import7.ComponentFactory<import0.DashboardComponent> = new import7.ComponentFactory<import0.DashboardComponent>('tr-dashboard',View_DashboardComponent_Host0,import0.DashboardComponent);
const styles_DashboardComponent:any[] = [import8.styles];
var renderType_DashboardComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_DashboardComponent,{});
export class View_DashboardComponent0 extends import1.AppView<import0.DashboardComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import9.DashboardSearchComponent>;
  _DashboardSearchComponent_4_3:import10.Wrapper_DashboardSearchComponent;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLink_15_3:import11.Wrapper_RouterLink;
  _RouterLinkActive_15_4:import12.Wrapper_RouterLinkActive;
  _query_RouterLink_15_0:import13.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import13.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLink_18_3:import11.Wrapper_RouterLink;
  _RouterLinkActive_18_4:import12.Wrapper_RouterLinkActive;
  _query_RouterLink_18_0:import13.QueryList<any>;
  _query_RouterLinkWithHref_18_1:import13.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _RouterLink_24_3:import11.Wrapper_RouterLink;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _vc_40:import14.ViewContainer;
  _RouterOutlet_40_5:import15.Wrapper_RouterOutlet;
  _text_41:any;
  _text_42:any;
  _arr_56:any;
  _arr_57:any;
  _arr_58:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardComponent0,renderType_DashboardComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_56 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_57 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_58 = import3.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','ui centered grid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','search sixteen wide column'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'tr-dashboard-search',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import10.View_DashboardSearchComponent0(this.viewUtils,this,4,this._el_4);
    this._DashboardSearchComponent_4_3 = new import10.Wrapper_DashboardSearchComponent(this.parentView.injectorGet(import16.Store,this.parentIndex),this.parentView.injectorGet(import17.Router,this.parentIndex));
    this.compView_4.create(this._DashboardSearchComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','fourteen wide column'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','ui centered grid button-collection'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','four wide column'),(null as any));
    this._text_12 = this.renderer.createText(this._el_9,'\n\n      ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','trips-type eight wide center aligned column'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'button',new import3.InlineArray4(4,'class','ui left attached big button','routerLinkActive','active'),(null as any));
    this._RouterLink_15_3 = new import11.Wrapper_RouterLink(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_15_4 = new import12.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import19.ElementRef(this._el_15),this.renderer);
    this._query_RouterLink_15_0 = new import13.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import13.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'\n            Feeds\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_13,'button',new import3.InlineArray4(4,'class','right attached ui big button','routerLinkActive','active'),(null as any));
    this._RouterLink_18_3 = new import11.Wrapper_RouterLink(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_18_4 = new import12.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import19.ElementRef(this._el_18),this.renderer);
    this._query_RouterLink_18_0 = new import13.QueryList<any>();
    this._query_RouterLinkWithHref_18_1 = new import13.QueryList<any>();
    this._text_19 = this.renderer.createText(this._el_18,'\n            Trending\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._text_21 = this.renderer.createText(this._el_9,'\n\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','create-button four wide right aligned column'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray4(4,'class','ui animated big button','tabindex','0'),(null as any));
    this._RouterLink_24_3 = new import11.Wrapper_RouterLink(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex));
    this._text_25 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','visible content'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'i',new import3.InlineArray2(2,'class','file text icon'),(null as any));
    this._text_29 = this.renderer.createText(this._el_26,'\n            Publish Trip\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','hidden content'),(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_31,'i',new import3.InlineArray2(2,'class','plus icon'),(null as any));
    this._text_33 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_35 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_37 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','sixteen wide column'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_40 = new import14.ViewContainer(40,38,this,this._el_40);
    this._RouterOutlet_40_5 = new import15.Wrapper_RouterOutlet(this.parentView.injectorGet(import20.RouterOutletMap,this.parentIndex),this._vc_40.vcRef,this.parentView.injectorGet(import21.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_41 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._text_42 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.DashboardSearchComponent) && (4 === requestNodeIndex))) { return this._DashboardSearchComponent_4_3.context; }
    if (((token === import22.RouterLink) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLink_15_3.context; }
    if (((token === import23.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4.context; }
    if (((token === import22.RouterLink) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLink_18_3.context; }
    if (((token === import23.RouterLinkActive) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkActive_18_4.context; }
    if (((token === import22.RouterLink) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLink_24_3.context; }
    if (((token === import24.RouterOutlet) && (40 === requestNodeIndex))) { return this._RouterOutlet_40_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DashboardSearchComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_15_0_0:any = this._arr_56('feeds');
    this._RouterLink_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLink_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'active';
    this._RouterLinkActive_15_4.check_routerLinkActive(currVal_15_1_0,throwOnChange,false);
    this._RouterLinkActive_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_18_0_0:any = this._arr_57('trending');
    this._RouterLink_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLink_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_1_0:any = 'active';
    this._RouterLinkActive_18_4.check_routerLinkActive(currVal_18_1_0,throwOnChange,false);
    this._RouterLinkActive_18_4.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_24_0_0:any = this._arr_58('/trips','new');
    this._RouterLink_24_3.check_routerLink(currVal_24_0_0,throwOnChange,false);
    this._RouterLink_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    this._RouterOutlet_40_5.ngDoCheck(this,this._el_40,throwOnChange);
    this._vc_40.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset([this._RouterLink_15_3.context]);
        this._RouterLinkActive_15_4.context.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset(([] as any[]));
        this._RouterLinkActive_15_4.context.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_18_0.dirty) {
        this._query_RouterLink_18_0.reset([this._RouterLink_18_3.context]);
        this._RouterLinkActive_18_4.context.links = this._query_RouterLink_18_0;
        this._query_RouterLink_18_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_18_1.dirty) {
        this._query_RouterLinkWithHref_18_1.reset(([] as any[]));
        this._RouterLinkActive_18_4.context.linksWithHrefs = this._query_RouterLinkWithHref_18_1;
        this._query_RouterLinkWithHref_18_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_18_4.context.ngAfterContentInit(); }
    }
    this.compView_4.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_40.destroyNestedViews();
    this.compView_4.destroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this._RouterLinkActive_18_4.ngOnDestroy();
    this._RouterOutlet_40_5.ngOnDestroy();
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_15_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_24_3.handleEvent(eventName,$event) && result);
    return result;
  }
}