/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.search.row[_ngcontent-%COMP%]{\n  margin-top: 1%;\n}\n\n.trips-type[_ngcontent-%COMP%] {\n  .button {\n    background: white;\n    box-shadow: none !important;\n    font-weight: 400;\n    box-shadow: none !important;\n    &.active {\n      background: #E74C3C !important;\n      color: white !important;\n    }\n  }\n\n  .ui.active.button {\n    background: #E74C3C !important;\n    color: white !important;\n  }\n\n  button:not(:first-child) {\n    margin-left: -0.2rem;\n  }\n}\n\n.create-button[_ngcontent-%COMP%] {\n  .button {\n    background: white;\n    color: #E74C3C;\n  }\n}\n\n.button-collection[_ngcontent-%COMP%] {\n   margin-bottom: -2rem;\n}'];