/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../../src/app/components/dashboard/index';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from 'ng2-validation/dist/directives';
import * as import6 from 'ng2-slim-loading-bar/index';
import * as import7 from '@angular/common/src/common_module';
import * as import8 from 'angular2-moment/moment.module';
import * as import9 from 'ng2-toasty/index';
import * as import10 from 'angular2-material-datepicker/src/datepicker.module';
import * as import11 from 'primeng/components/button/button';
import * as import12 from 'primeng/components/inputtext/inputtext';
import * as import13 from 'primeng/components/calendar/calendar';
import * as import14 from 'angular2-infinite-scroll/src/index';
import * as import15 from '../../../../../src/app/shared/index';
import * as import16 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import17 from '@angular/forms/src/form_builder';
import * as import18 from 'ng2-slim-loading-bar/src/slim-loading-bar.service';
import * as import19 from '@angular/common/src/localization';
import * as import20 from 'ng2-toasty/src/toasty.service';
import * as import21 from 'angular2-infinite-scroll/src/axis-resolver';
import * as import22 from 'angular2-infinite-scroll/src/position-resolver';
import * as import23 from '@angular/core/src/di/injector';
import * as import24 from './dashboard.component.ngfactory';
import * as import25 from './feed-trips/feed-trips.component.ngfactory';
import * as import26 from './trending-trips/trending-trips.component.ngfactory';
import * as import27 from '@angular/core/src/i18n/tokens';
import * as import28 from '../../../../../src/app/components/dashboard/dashboard.component';
import * as import29 from '../../../../../src/app/components/dashboard/feed-trips/feed-trips.component';
import * as import30 from '../../../../../src/app/components/dashboard/trending-trips/trending-trips.component';
import * as import31 from '@angular/router/src/router_config_loader';
class DashboardModuleInjector extends import0.NgModuleInjector<import1.DashboardModule> {
  _RouterModule_0:import2.RouterModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _CustomFormsModule_3:import5.CustomFormsModule;
  _ReactiveFormsModule_4:import4.ReactiveFormsModule;
  _SlimLoadingBarModule_5:import6.SlimLoadingBarModule;
  _CommonModule_6:import7.CommonModule;
  _MomentModule_7:import8.MomentModule;
  _ToastyModule_8:import9.ToastyModule;
  _DatepickerModule_9:import10.DatepickerModule;
  _ButtonModule_10:import11.ButtonModule;
  _InputTextModule_11:import12.InputTextModule;
  _CalendarModule_12:import13.CalendarModule;
  _InfiniteScrollModule_13:import14.InfiniteScrollModule;
  _SharedModule_14:import15.SharedModule;
  _DashboardModule_15:import1.DashboardModule;
  __RadioControlRegistry_16:import16.RadioControlRegistry;
  __FormBuilder_17:import17.FormBuilder;
  __SlimLoadingBarService_18:import18.SlimLoadingBarService;
  __NgLocalization_19:import19.NgLocaleLocalization;
  __ToastyConfig_20:import20.ToastyConfig;
  __ToastyService_21:any;
  __AxisResolverFactory_22:import21.AxisResolverFactory;
  __PositionResolverFactory_23:import22.PositionResolverFactory;
  __ROUTES_24:any[];
  constructor(parent:import23.Injector) {
    super(parent,[
      import24.DashboardComponentNgFactory,
      import25.FeedTripsComponentNgFactory,
      import26.TrendingTripsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _RadioControlRegistry_16():import16.RadioControlRegistry {
    if ((this.__RadioControlRegistry_16 == null)) { (this.__RadioControlRegistry_16 = new import16.RadioControlRegistry()); }
    return this.__RadioControlRegistry_16;
  }
  get _FormBuilder_17():import17.FormBuilder {
    if ((this.__FormBuilder_17 == null)) { (this.__FormBuilder_17 = new import17.FormBuilder()); }
    return this.__FormBuilder_17;
  }
  get _SlimLoadingBarService_18():import18.SlimLoadingBarService {
    if ((this.__SlimLoadingBarService_18 == null)) { (this.__SlimLoadingBarService_18 = new import18.SlimLoadingBarService()); }
    return this.__SlimLoadingBarService_18;
  }
  get _NgLocalization_19():import19.NgLocaleLocalization {
    if ((this.__NgLocalization_19 == null)) { (this.__NgLocalization_19 = new import19.NgLocaleLocalization(this.parent.get(import27.LOCALE_ID))); }
    return this.__NgLocalization_19;
  }
  get _ToastyConfig_20():import20.ToastyConfig {
    if ((this.__ToastyConfig_20 == null)) { (this.__ToastyConfig_20 = new import20.ToastyConfig()); }
    return this.__ToastyConfig_20;
  }
  get _ToastyService_21():any {
    if ((this.__ToastyService_21 == null)) { (this.__ToastyService_21 = import20.toastyServiceFactory(this._ToastyConfig_20)); }
    return this.__ToastyService_21;
  }
  get _AxisResolverFactory_22():import21.AxisResolverFactory {
    if ((this.__AxisResolverFactory_22 == null)) { (this.__AxisResolverFactory_22 = new import21.AxisResolverFactory()); }
    return this.__AxisResolverFactory_22;
  }
  get _PositionResolverFactory_23():import22.PositionResolverFactory {
    if ((this.__PositionResolverFactory_23 == null)) { (this.__PositionResolverFactory_23 = new import22.PositionResolverFactory(this._AxisResolverFactory_22)); }
    return this.__PositionResolverFactory_23;
  }
  get _ROUTES_24():any[] {
    if ((this.__ROUTES_24 == null)) { (this.__ROUTES_24 = [
      ([] as any[]),
        [{
          path: 'dashboard',
          component: import28.DashboardComponent,
          children: [
            {
              path: '',
              redirectTo: 'feeds',
              pathMatch: 'full'
            }
            ,
            {
              path: 'feeds',
              component: import29.FeedTripsComponent
            }
            ,
            {
              path: 'trending',
              component: import30.TrendingTripsComponent
            }

          ]

        }
      ]
    ]
    ); }
    return this.__ROUTES_24;
  }
  createInternal():import1.DashboardModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._CustomFormsModule_3 = new import5.CustomFormsModule();
    this._ReactiveFormsModule_4 = new import4.ReactiveFormsModule();
    this._SlimLoadingBarModule_5 = new import6.SlimLoadingBarModule();
    this._CommonModule_6 = new import7.CommonModule();
    this._MomentModule_7 = new import8.MomentModule();
    this._ToastyModule_8 = new import9.ToastyModule();
    this._DatepickerModule_9 = new import10.DatepickerModule();
    this._ButtonModule_10 = new import11.ButtonModule();
    this._InputTextModule_11 = new import12.InputTextModule();
    this._CalendarModule_12 = new import13.CalendarModule();
    this._InfiniteScrollModule_13 = new import14.InfiniteScrollModule();
    this._SharedModule_14 = new import15.SharedModule();
    this._DashboardModule_15 = new import1.DashboardModule();
    return this._DashboardModule_15;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.CustomFormsModule)) { return this._CustomFormsModule_3; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.SlimLoadingBarModule)) { return this._SlimLoadingBarModule_5; }
    if ((token === import7.CommonModule)) { return this._CommonModule_6; }
    if ((token === import8.MomentModule)) { return this._MomentModule_7; }
    if ((token === import9.ToastyModule)) { return this._ToastyModule_8; }
    if ((token === import10.DatepickerModule)) { return this._DatepickerModule_9; }
    if ((token === import11.ButtonModule)) { return this._ButtonModule_10; }
    if ((token === import12.InputTextModule)) { return this._InputTextModule_11; }
    if ((token === import13.CalendarModule)) { return this._CalendarModule_12; }
    if ((token === import14.InfiniteScrollModule)) { return this._InfiniteScrollModule_13; }
    if ((token === import15.SharedModule)) { return this._SharedModule_14; }
    if ((token === import1.DashboardModule)) { return this._DashboardModule_15; }
    if ((token === import16.RadioControlRegistry)) { return this._RadioControlRegistry_16; }
    if ((token === import17.FormBuilder)) { return this._FormBuilder_17; }
    if ((token === import18.SlimLoadingBarService)) { return this._SlimLoadingBarService_18; }
    if ((token === import19.NgLocalization)) { return this._NgLocalization_19; }
    if ((token === import20.ToastyConfig)) { return this._ToastyConfig_20; }
    if ((token === import20.ToastyService)) { return this._ToastyService_21; }
    if ((token === import21.AxisResolverFactory)) { return this._AxisResolverFactory_22; }
    if ((token === import22.PositionResolverFactory)) { return this._PositionResolverFactory_23; }
    if ((token === import31.ROUTES)) { return this._ROUTES_24; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DashboardModuleNgFactory:import0.NgModuleFactory<import1.DashboardModule> = new import0.NgModuleFactory(DashboardModuleInjector,import1.DashboardModule);