/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['$appBaseColor[_ngcontent-%COMP%]:   #2C3E50[_ngcontent-%COMP%];\n$appActionColor[_ngcontent-%COMP%]:   #E74C3C[_ngcontent-%COMP%];'];