/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../_vars.scss.shim.ngstyle';
export const styles:any[] = [
  '.photo.icon[_ngcontent-%COMP%] {\n  height: 50px;\n  width: 50px;\n  color: $appBaseColor;\n  cursor: pointer;\n\n  &:before {\n    top: 22%;\n    position: relative;\n    left: 3%;\n  }\n}',
  import0.styles
]
;