/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../src/app/components/user/user-profile/user-followers/user-followers.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '../../../../../../../src/app/services/user.service';
import * as import11 from './user-followers.component.scss.shim.ngstyle';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '@angular/core/src/change_detection/change_detection_util';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/core/src/security';
import * as import18 from '../../../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import19 from '@angular/common/src/pipes/async_pipe';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/common/src/directives/ng_for';
export class Wrapper_UserFollowersComponent {
  /*private*/ _eventHandler:Function;
  context:import0.UserFollowersComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.UserFollowersComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_UserFollowersComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_UserFollowersComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.UserFollowersComponent>;
  _UserFollowersComponent_0_3:Wrapper_UserFollowersComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UserFollowersComponent_Host0,renderType_UserFollowersComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-user-followers',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_UserFollowersComponent0(this.viewUtils,this,0,this._el_0);
    this._UserFollowersComponent_0_3 = new Wrapper_UserFollowersComponent(this.injectorGet(import8.Store,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex),this.injectorGet(import10.UserService,this.parentIndex));
    this.compView_0.create(this._UserFollowersComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._UserFollowersComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.UserFollowersComponent) && (0 === requestNodeIndex))) { return this._UserFollowersComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._UserFollowersComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._UserFollowersComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const UserFollowersComponentNgFactory:import7.ComponentFactory<import0.UserFollowersComponent> = new import7.ComponentFactory<import0.UserFollowersComponent>('tr-user-followers',View_UserFollowersComponent_Host0,import0.UserFollowersComponent);
const styles_UserFollowersComponent:any[] = [import11.styles];
class View_UserFollowersComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_UserFollowersComponent2,renderType_UserFollowersComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','following'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray2(2,'class','big teal check square icon'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_UserFollowersComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import12.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import13.Wrapper_NgIf;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_UserFollowersComponent1,renderType_UserFollowersComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_39 = import14.UNINITIALIZED;
    this._expr_40 = import14.UNINITIALIZED;
    this._expr_41 = import14.UNINITIALIZED;
    this._expr_42 = import14.UNINITIALIZED;
    this._expr_43 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','ui grid follower-list'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','two wide column'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'img',new import3.InlineArray2(2,'class','ui avatar image'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','twelve wide column'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','name'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'span',new import3.InlineArray2(2,'class','info'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_14,'span',new import3.InlineArray2(2,'class','info'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_14,'span',new import3.InlineArray2(2,'class','info'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._text_25 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','two wide column'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._vc_29 = new import12.ViewContainer(29,27,this,this._anchor_29);
    this._TemplateRef_29_5 = new import15.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import13.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_27,'div',new import3.InlineArray2(2,'class','not-following'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n        Follow\n      ',(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import16.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_29_0_0:any = this.context.$implicit.is_followed_by_current_user;
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    const currVal_39:any = ((this.context.$implicit == null)? (null as any): this.context.$implicit.profile_pic.url);
    if (import3.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_39));
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = import3.inlineInterpolate(1,'\n        ',((this.context.$implicit == null)? (null as any): this.context.$implicit.name),'\n      ');
    if (import3.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setText(this._text_12,currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = import3.inlineInterpolate(1,'',((this.context.$implicit == null)? (null as any): this.context.$implicit.total_trips),' Trips');
    if (import3.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setText(this._text_17,currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = import3.inlineInterpolate(1,'',((this.context.$implicit == null)? (null as any): this.context.$implicit.total_followers),' Followers');
    if (import3.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setText(this._text_20,currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = import3.inlineInterpolate(1,'',((this.context.$implicit == null)? (null as any): this.context.$implicit.total_following),' Following');
    if (import3.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setText(this._text_23,currVal_43);
      this._expr_43 = currVal_43;
    }
  }
  destroyInternal():void {
    this._vc_29.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 29)) { return new View_UserFollowersComponent2(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    return (null as any);
  }
}
var renderType_UserFollowersComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_UserFollowersComponent,{});
export class View_UserFollowersComponent0 extends import1.AppView<import0.UserFollowersComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import12.ViewContainer;
  _TemplateRef_0_5:any;
  _NgFor_0_6:import18.Wrapper_NgFor;
  _text_1:any;
  _pipe_async_0:import19.AsyncPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UserFollowersComponent0,renderType_UserFollowersComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import12.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import15.TemplateRef_(this,0,this._anchor_0);
    this._NgFor_0_6 = new import18.Wrapper_NgFor(this._vc_0.vcRef,this._TemplateRef_0_5,this.parentView.injectorGet(import20.IterableDiffers,this.parentIndex),this.ref);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_async_0 = new import19.AsyncPipe(this.ref);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import21.NgFor) && (0 === requestNodeIndex))) { return this._NgFor_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import14.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_0_0_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.followersList$));
    this._NgFor_0_6.check_ngForOf(currVal_0_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this._pipe_async_0.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_UserFollowersComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}