/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['.follower-list[_ngcontent-%COMP%] {\n	padding: 10px;\n  border-bottom: 1px solid #eee;\n}\n\n.square[_ngcontent-%COMP%] {\n	transform: translateY(60%);\n  position: relative;\n}\n\n.info[_ngcontent-%COMP%] {\n	margin-right: 1.5rem;\n	color: #aaa;\n}\n\n.name[_ngcontent-%COMP%] {\n	font-weight: 400;\n	font-size: 1.3rem;\n  margin-bottom: 9px;\n}'];
//# sourceMappingURL=user-followers.component.scss.shim.ngstyle.js.map