/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['.my-card[_ngcontent-%COMP%] {\n  width: 75%;\n  margin-bottom: 40px !important; \n}'];
//# sourceMappingURL=user-media.component.scss.shim.ngstyle.js.map