/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../src/app/components/trips/trip-detail/trip-detail-header/trip-detail-header.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@ngrx/store/src/store';
import * as import10 from '../../../../../../../src/app/services/user-auth.service';
import * as import11 from './trip-detail-header.component.scss.shim.ngstyle';
import * as import12 from '../../../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import15 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/common/src/directives/ng_class';
import * as import18 from '../../../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import19 from '../../../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '@angular/common/src/pipes/async_pipe';
import * as import21 from '../../../../../../../src/app/pipes/humanize';
import * as import22 from '@angular/router/src/router';
import * as import23 from '@angular/router/src/router_state';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/router/src/directives/router_link';
import * as import26 from '@angular/common/src/directives/ng_if';
import * as import27 from '@angular/core/src/security';
export class Wrapper_TripDetailHeaderComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TripDetailHeaderComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.TripDetailHeaderComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_trip(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.trip = currValue;
      this._expr_0 = currValue;
    }
  }
  check_tripUser(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.tripUser = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TripDetailHeaderComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TripDetailHeaderComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.TripDetailHeaderComponent>;
  _TripDetailHeaderComponent_0_3:Wrapper_TripDetailHeaderComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TripDetailHeaderComponent_Host0,renderType_TripDetailHeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-trip-detail-header',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TripDetailHeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._TripDetailHeaderComponent_0_3 = new Wrapper_TripDetailHeaderComponent(this.injectorGet(import9.Store,this.parentIndex),this.injectorGet(import10.UserAuthService,this.parentIndex));
    this.compView_0.create(this._TripDetailHeaderComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._TripDetailHeaderComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TripDetailHeaderComponent) && (0 === requestNodeIndex))) { return this._TripDetailHeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._TripDetailHeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TripDetailHeaderComponentNgFactory:import8.ComponentFactory<import0.TripDetailHeaderComponent> = new import8.ComponentFactory<import0.TripDetailHeaderComponent>('tr-trip-detail-header',View_TripDetailHeaderComponent_Host0,import0.TripDetailHeaderComponent);
const styles_TripDetailHeaderComponent:any[] = [import11.styles];
class View_TripDetailHeaderComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import12.Wrapper_NgClass;
  _text_3:any;
  _text_4:any;
  _map_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_TripDetailHeaderComponent1,renderType_TripDetailHeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_6 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        active: p0,
        inactive: p1
      }
      ;
    });
    this._expr_7 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','follow-user'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray2(2,'class','add user icon'),(null as any));
    this._NgClass_2_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import14.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import15.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgClass_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = 'add user icon';
    this._NgClass_2_3.check_klass(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = this._map_6((this.parentView.context.tripFollowState() == 'active'),(this.parentView.context.tripFollowState() == 'inactive'));
    this._NgClass_2_3.check_ngClass(currVal_2_0_1,throwOnChange,false);
    this._NgClass_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_7:any = import3.inlineInterpolate(1,'\n  ',((this.parentView.context.tripFollowState() == 'inactive')? 'Follow': 'Following'),'\n');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_4,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onToggleFollow()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_TripDetailHeaderComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_TripDetailHeaderComponent,{});
export class View_TripDetailHeaderComponent0 extends import2.AppView<import0.TripDetailHeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLink_8_3:import18.Wrapper_RouterLink;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import13.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import19.Wrapper_NgIf;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _NgClass_25_3:import12.Wrapper_NgClass;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  _arr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  _pipe_async_0:import20.AsyncPipe;
  /*private*/ _expr_39:any;
  _pipe_humanize_1:import21.HumanizePipe;
  _pipe_humanize_1_0:any;
  _map_42:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TripDetailHeaderComponent0,renderType_TripDetailHeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckOnce);
    this._expr_33 = import1.UNINITIALIZED;
    this._expr_34 = import1.UNINITIALIZED;
    this._arr_35 = import3.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_36 = import1.UNINITIALIZED;
    this._expr_37 = import1.UNINITIALIZED;
    this._expr_39 = import1.UNINITIALIZED;
    this._map_42 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','image'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','trip-name'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','trip-user'),(null as any));
    this._RouterLink_8_3 = new import18.Wrapper_RouterLink(this.parentView.injectorGet(import22.Router,this.parentIndex),this.parentView.injectorGet(import23.ActivatedRoute,this.parentIndex));
    this._text_9 = this.renderer.createText(this._el_8,'\n  ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray2(2,'class',''),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n  ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray2(2,'class','user-name'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,parentRenderNode,'hr',new import3.InlineArray2(2,'class','header-divider'),(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_18 = new import13.ViewContainer(18,(null as any),this,this._anchor_18);
    this._TemplateRef_18_5 = new import24.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import19.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','trip-likes'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','like-trip'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'i',new import3.InlineArray2(2,'class','thumbs up huge icon'),(null as any));
    this._NgClass_25_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import14.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import15.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText(this._el_25,'\n  ',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    this._pipe_async_0 = new import20.AsyncPipe(this.ref);
    this._pipe_humanize_1 = new import21.HumanizePipe();
    this._pipe_humanize_1_0 = import3.pureProxy1(this._pipe_humanize_1.transform.bind(this._pipe_humanize_1));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_25));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.RouterLink) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLink_8_3.context; }
    if (((token === import24.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import26.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import17.NgClass) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgClass_25_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_8_0_0:any = this._arr_35('/user',this.context.tripUser.id);
    this._RouterLink_8_3.check_routerLink(currVal_8_0_0,throwOnChange,false);
    this._RouterLink_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    valUnwrapper.reset();
    const currVal_18_0_0:boolean = !valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.belongsToLoggedInUser()));
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    const currVal_25_0_0:any = 'thumbs up huge icon';
    this._NgClass_25_3.check_klass(currVal_25_0_0,throwOnChange,false);
    const currVal_25_0_1:any = this._map_42((this.context.tripLikeState() == 'active'));
    this._NgClass_25_3.check_ngClass(currVal_25_0_1,throwOnChange,false);
    this._NgClass_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    const currVal_33:any = this.context.formatImageUrl(((this.context.trip == null)? (null as any): this.context.trip.thumbnail_image_url));
    if (import3.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_33));
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = import3.inlineInterpolate(1,'\n  ',((this.context.trip == null)? (null as any): this.context.trip.name),'\n');
    if (import3.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setText(this._text_6,currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_36:any = ((this.context.tripUser.profile_pic == null)? (null as any): this.context.tripUser.profile_pic.url);
    if (import3.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_10,'src',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_36));
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = import3.inlineInterpolate(1,'\n    ',this.context.tripUser.name,'\n  ');
    if (import3.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setText(this._text_13,currVal_37);
      this._expr_37 = currVal_37;
    }
    valUnwrapper.reset();
    const currVal_39:any = import3.inlineInterpolate(1,'\n  ',valUnwrapper.unwrap(import3.castByValue(this._pipe_humanize_1_0,this._pipe_humanize_1.transform)(((this.context.trip == null)? (null as any): this.context.trip.trip_likes_count))),' Likes\n');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_39,currVal_39))) {
      this.renderer.setText(this._text_21,currVal_39);
      this._expr_39 = currVal_39;
    }
  }
  destroyInternal():void {
    this._vc_18.destroyNestedViews();
    this._pipe_async_0.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 18)) { return new View_TripDetailHeaderComponent1(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    return (null as any);
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_8_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onToggleLike()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}