/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/effects/index';
import * as import2 from '@ngrx/effects/src/effects.module';
import * as import3 from '@ngrx/effects/src/actions';
import * as import4 from '../../../../src/app/effects/user.effects';
import * as import5 from '../../../../src/app/effects/user-auth.effect';
import * as import6 from '../../../../src/app/effects/trips.effects';
import * as import7 from '../../../../src/app/effects/instagram.effects';
import * as import8 from '../../../../src/app/effects/comments.effects';
import * as import9 from '@ngrx/effects/src/effects-subscription';
import * as import10 from '@angular/core/src/di/injector';
import * as import11 from '@ngrx/store/src/dispatcher';
import * as import12 from '@ngrx/effects/src/bootstrap-listener';
import * as import13 from '../../../../src/app/services/user.service';
import * as import14 from '../../../../src/app/services/server-auth.service';
import * as import15 from '../../../../src/app/services/user-auth.service';
import * as import16 from '@ngrx/store/src/store';
import * as import17 from '../../../../src/app/services/trips.service';
import * as import18 from '../../../../src/app/services/instagram-integration.service';
import * as import19 from '@angular/core/src/application_tokens';
class AppEffectsModuleInjector extends import0.NgModuleInjector<import1.AppEffectsModule> {
  _EffectsModule_0:import2.EffectsModule;
  _AppEffectsModule_1:import1.AppEffectsModule;
  __Actions_2:import3.Actions;
  _UserEffects_3:import4.UserEffects;
  _UserAuthEffects_4:import5.UserAuthEffects;
  _TripsEffects_5:import6.TripsEffects;
  _InstagramEffects_6:import7.InstagramEffects;
  _CommentEffects_7:import8.CommentEffects;
  _effects_8:any[];
  _EffectsSubscription_9:import9.EffectsSubscription;
  __APP_BOOTSTRAP_LISTENER_10:any[];
  constructor(parent:import10.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _Actions_2():import3.Actions {
    if ((this.__Actions_2 == null)) { (this.__Actions_2 = new import3.Actions(this.parent.get(import11.Dispatcher))); }
    return this.__Actions_2;
  }
  get _APP_BOOTSTRAP_LISTENER_10():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_10 == null)) { (this.__APP_BOOTSTRAP_LISTENER_10 = [import12.runAfterBootstrapEffects(this,this._EffectsSubscription_9)]); }
    return this.__APP_BOOTSTRAP_LISTENER_10;
  }
  createInternal():import1.AppEffectsModule {
    this._EffectsModule_0 = new import2.EffectsModule();
    this._AppEffectsModule_1 = new import1.AppEffectsModule();
    this._UserEffects_3 = new import4.UserEffects(this._Actions_2,this.parent.get(import13.UserService),this.parent.get(import14.ServerAuthService));
    this._UserAuthEffects_4 = new import5.UserAuthEffects(this._Actions_2,this.parent.get(import15.UserAuthService),this.parent.get(import14.ServerAuthService),this.parent.get(import16.Store));
    this._TripsEffects_5 = new import6.TripsEffects(this._Actions_2,this.parent.get(import17.TripsService));
    this._InstagramEffects_6 = new import7.InstagramEffects(this._Actions_2,this.parent.get(import18.InstagramIntegrationService));
    this._CommentEffects_7 = new import8.CommentEffects(this._Actions_2,this.parent.get(import17.TripsService),this.parent.get(import16.Store));
    this._effects_8 = [
      this._UserEffects_3,
      this._UserAuthEffects_4,
      this._TripsEffects_5,
      this._InstagramEffects_6,
      this._CommentEffects_7
    ]
    ;
    this._EffectsSubscription_9 = new import9.EffectsSubscription(this.parent.get(import16.Store),this.parent.get(import9.EffectsSubscription,(null as any)),this._effects_8);
    return this._AppEffectsModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.EffectsModule)) { return this._EffectsModule_0; }
    if ((token === import1.AppEffectsModule)) { return this._AppEffectsModule_1; }
    if ((token === import3.Actions)) { return this._Actions_2; }
    if ((token === import4.UserEffects)) { return this._UserEffects_3; }
    if ((token === import5.UserAuthEffects)) { return this._UserAuthEffects_4; }
    if ((token === import6.TripsEffects)) { return this._TripsEffects_5; }
    if ((token === import7.InstagramEffects)) { return this._InstagramEffects_6; }
    if ((token === import8.CommentEffects)) { return this._CommentEffects_7; }
    if ((token === import9.effects)) { return this._effects_8; }
    if ((token === import9.EffectsSubscription)) { return this._EffectsSubscription_9; }
    if ((token === import19.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_10; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._EffectsSubscription_9.ngOnDestroy();
  }
}
export const AppEffectsModuleNgFactory:import0.NgModuleFactory<import1.AppEffectsModule> = new import0.NgModuleFactory(AppEffectsModuleInjector,import1.AppEffectsModule);