/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../_vars.scss.shim.ngstyle';
export const styles:any[] = [
  '.trip[_ngcontent-%COMP%] {\n	margin-top: 30px;\n}\n\n.trip-form[_ngcontent-%COMP%] {\n	padding: 0 !important;\n}\n\n.trip-title[_ngcontent-%COMP%] {\n	width: 70% !important;\n	font-size: 3rem !important;\n  font-weight: bold;\n	margin-left: -2rem !important;\n	&:focus {\n		background: none !important;\n	}\n}\n\n.trip-description[_ngcontent-%COMP%] {\n	font-size: 1.5rem !important;\n	min-height: 3rem !important;\n	text-align: justify;\n}\n\n.save-button[_ngcontent-%COMP%] {\n	float: right;\n	background: $appActionColor;\n	color: white;\n	margin-top: 2.3rem;\n}\n\ninput[_ngcontent-%COMP%] {\n	border: none !important;\n}\n\ntextarea[_ngcontent-%COMP%] {\n	border: none !important;\n	resize: none !important;\n}\n\n.place-form[_ngcontent-%COMP%] {\n	margin-top: 30px !important;\n	padding: 0 !important;\n	background: none !important;\n	box-shadow: none !important;\n	.ui.card {\n		width: 100%;\n	}\n	.remove.icon {\n		cursor: pointer;\n		font-size: 2em;\n	}\n}\n\n.trip-form[_ngcontent-%COMP%] {\n	background: none !important;\n	box-shadow: none !important;\n\n	input {\n		background: none;\n	}\n\n	textarea {\n		background: none;\n	}\n}',
  import0.styles
]
;