/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../_vars.scss.shim.ngstyle';
export const styles:any[] = [
  '.trip[_ngcontent-%COMP%] {\n	margin-top: 30px;\n}\n\n.trip-form[_ngcontent-%COMP%] {\n	padding: 0 !important;\n}\n\n.trip-title[_ngcontent-%COMP%] {\n	color: #939799 !important;\n  font-weight: 700;\n	min-height: 2em !important;\n	height: 2em !important;\n	width: 70% !important;\n	font-size: 3rem !important;\n	margin-left: -2rem !important;\n	&:focus {\n		background: none !important;\n	}\n}\n\n.trip-description[_ngcontent-%COMP%] {\n	color: #939799 !important;\n	font-size: 1.5rem !important;\n	min-height: 3rem !important;\n	text-align: justify;\n}\n\n.save-button[_ngcontent-%COMP%] {\n	border-radius: 0 !important;\n	float: right;\n	background: $appActionColor;\n	color: white;\n	margin-top: 2.3rem;\n}\n\ninput[_ngcontent-%COMP%] {\n	border: none !important;\n}\n\ntextarea[_ngcontent-%COMP%] {\n	border: none !important;\n	resize: none !important;\n}\n\n.place-form[_ngcontent-%COMP%] {\n	padding-top: 0px !important;\n	padding-bottom: 0px !important;\n	position: relative;\n	.place {\n		margin-bottom: 50px;\n	}\n	.remove-icon-background {\n		background: white;\n    width: 2.2em;\n    position: absolute;\n    right: -13px;\n    z-index: 1;\n    height: 2.2em;\n    border-radius: 20px;\n    top: -6px;\n	}\n	.icon {\n		font-size: 4em !important;\n		color: #CBCBCB;\n    position: absolute;\n    right: -35px;\n    top: -5px;\n    z-index: 1;\n		cursor: pointer;\n	}\n}\n\n.trip-form[_ngcontent-%COMP%] {\n	background: none !important;\n	box-shadow: none !important;\n\n	input {\n		background: none;\n	}\n\n	textarea {\n		background: none;\n	}\n}\n\n\n.add-place[_ngcontent-%COMP%] {\n	margin-top: 8px;\n	padding: 0 !important;\n  color: #F12732;\n	.icon {\n		cursor: pointer;\n		font-size: 4rem;\n    width: 100%;\n		background: #FAFAFA;\n    padding-top: 23px;\n    padding-bottom: 51px;\n	}\n}',
  import0.styles
]
;