/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.loader-image[_ngcontent-%COMP%] {\n  margin: 6%;\n  width: 10%;\n  transform: translate(0%, 40%);\n}'];