/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../src/app/components/dashboard/dashboard-search/dashboard-search.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/router/src/router';
import * as import10 from './dashboard-search.component.scss.shim.ngstyle';
import * as import11 from '@angular/core/src/animation/animation_transition';
import * as import12 from '@angular/core/src/animation/animation_sequence_player';
import * as import13 from '@angular/core/src/animation/animation_styles';
import * as import14 from '@angular/core/src/animation/animation_style_util';
import * as import15 from '@angular/core/src/animation/animation_keyframe';
import * as import16 from '@angular/core/src/animation/animation_player';
import * as import17 from '../../../../../../src/app/components/shared/search/dashboard-search-filter/dashboard-search-filter.component';
import * as import18 from '../../shared/search/dashboard-search-filter/dashboard-search-filter.component.ngfactory';
import * as import19 from '@angular/core/src/change_detection/change_detection_util';
export class Wrapper_DashboardSearchComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DashboardSearchComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.DashboardSearchComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_DashboardSearchComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_DashboardSearchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.DashboardSearchComponent>;
  _DashboardSearchComponent_0_3:Wrapper_DashboardSearchComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardSearchComponent_Host0,renderType_DashboardSearchComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-dashboard-search',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DashboardSearchComponent0(this.viewUtils,this,0,this._el_0);
    this._DashboardSearchComponent_0_3 = new Wrapper_DashboardSearchComponent(this.injectorGet(import8.Store,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._DashboardSearchComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._DashboardSearchComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DashboardSearchComponent) && (0 === requestNodeIndex))) { return this._DashboardSearchComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DashboardSearchComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DashboardSearchComponentNgFactory:import7.ComponentFactory<import0.DashboardSearchComponent> = new import7.ComponentFactory<import0.DashboardSearchComponent>('tr-dashboard-search',View_DashboardSearchComponent_Host0,import0.DashboardSearchComponent);
const styles_DashboardSearchComponent:any[] = [import10.styles];
var DashboardSearchComponent_flyInDown_states:any = {
  'in': {},
  '*': {},
  'void': {}
}
;
function DashboardSearchComponent_flyInDown_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import11.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'flyInDown'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = DashboardSearchComponent_flyInDown_states['*'];
  var startStateStyles:any = DashboardSearchComponent_flyInDown_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = DashboardSearchComponent_flyInDown_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import12.AnimationSequencePlayer([view.renderer.animate(element,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'top': '-5%',
          'opacity': '0'
        }

      ]
      )),import14.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import15.AnimationKeyframe(0,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[{}]))),
        new import15.AnimationKeyframe(1,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,(null as any),previousPlayers)]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import16.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import14.renderStyles(element,view.renderer,import14.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import12.AnimationSequencePlayer(previousPlayers).destroy();
  import14.renderStyles(element,view.renderer,import14.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'flyInDown',player);
  return new import11.AnimationTransition(player,currentState,nextState,totalTime);
}
var renderType_DashboardSearchComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_DashboardSearchComponent,{flyInDown: DashboardSearchComponent_flyInDown_factory});
export class View_DashboardSearchComponent0 extends import1.AppView<import0.DashboardSearchComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  compView_30:import1.AppView<import17.DashboardSearchFilterComponent>;
  _DashboardSearchFilterComponent_30_3:import18.Wrapper_DashboardSearchFilterComponent;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  /*private*/ _expr_40:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardSearchComponent0,renderType_DashboardSearchComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_40 = import19.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','search-box-cover'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','image search-box-cover-div'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'img',new import3.InlineArray4(4,'class','cover-image','src','http://wallpaperlayer.com/img/2015/1/blurred-city-lights-7598-7892-hd-wallpapers.jpg'),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','search-box'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','ui grid'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'h1',new import3.InlineArray2(2,'class','text-white text-center column'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'i',new import3.InlineArray2(2,'class','teal large marker icon'),(null as any));
    this._text_15 = this.renderer.createText(this._el_12,'\n            Explore\n            the Unexplored\n          ',(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'h2',new import3.InlineArray2(2,'class','text-white text-center column'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'i',new import3.InlineArray2(2,'class','orange large map signs icon'),(null as any));
    this._text_23 = this.renderer.createText(this._el_20,'\n            Discover\n            Trips Shared by Real Travellers\n          ',(null as any));
    this._text_24 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','column'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'tr-dashboard-search-filter',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_30 = new import18.View_DashboardSearchFilterComponent0(this.viewUtils,this,30,this._el_30);
    this._DashboardSearchFilterComponent_30_3 = new import18.Wrapper_DashboardSearchFilterComponent();
    this.compView_30.create(this._DashboardSearchFilterComponent_30_3.context);
    this._text_31 = this.renderer.createText(this._el_28,'\n          ',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._text_34 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray2(2,'keywordEntered',(null as any)),this.eventHandler(this.handleEvent_30));
    this._DashboardSearchFilterComponent_30_3.subscribe(this,this.eventHandler(this.handleEvent_30),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.DashboardSearchFilterComponent) && (30 === requestNodeIndex))) { return this._DashboardSearchFilterComponent_30_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_40:any = 'in';
    if (import3.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      var animationTransition_flyInDown:any = this.componentType.animations['flyInDown'](this,this._el_6,((this._expr_40 == import19.UNINITIALIZED)? 'void': this._expr_40),((currVal_40 == import19.UNINITIALIZED)? 'void': currVal_40));
      this._expr_40 = currVal_40;
    }
    this._DashboardSearchFilterComponent_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    this.compView_30.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_30.destroy();
    this._DashboardSearchFilterComponent_30_3.ngOnDestroy();
  }
  detachInternal():void {
    var animationTransition_flyInDown:any = this.componentType.animations['flyInDown'](this,this._el_6,this._expr_40,'void');
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'keywordEntered')) {
      const pd_sub_0:any = ((<any>this.context.onSearch($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}