/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['.card[_ngcontent-%COMP%] {\n  box-shadow: 1px 1px 5px #aaa;\n}\n\n.my-pagination[_ngcontent-%COMP%] {\n  text-align: center !important;\n}'];
//# sourceMappingURL=trending-trips.component.scss.shim.ngstyle.js.map