/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../src/app/components/user/user-profile/user-profile.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '../../../../../../src/app/services/cloudinary-integration.service';
import * as import11 from '../../../../../../src/app/services/user.service';
import * as import12 from './user-profile.component.scss.shim.ngstyle';
import * as import13 from '@angular/core/src/animation/animation_transition';
import * as import14 from '@angular/core/src/animation/animation_sequence_player';
import * as import15 from '@angular/core/src/animation/animation_styles';
import * as import16 from '@angular/core/src/animation/animation_style_util';
import * as import17 from '@angular/core/src/animation/animation_keyframe';
import * as import18 from '@angular/core/src/animation/animation_player';
import * as import19 from '@angular/core/src/linker/view_container';
import * as import20 from '@angular/core/src/change_detection/change_detection_util';
import * as import21 from '@angular/core/src/security';
import * as import22 from '../../../../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import23 from '../../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import24 from '../../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import25 from '../../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import26 from '../../../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import27 from '@angular/core/src/linker/query_list';
import * as import28 from '@angular/common/src/pipes/async_pipe';
import * as import29 from '@angular/router/src/router_outlet_map';
import * as import30 from '@angular/core/src/linker/component_factory_resolver';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import33 from '@angular/core/src/linker/element_ref';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/router/src/router';
import * as import36 from '@angular/router/src/directives/router_outlet';
import * as import37 from '@angular/common/src/directives/ng_if';
import * as import38 from '@angular/common/src/directives/ng_class';
import * as import39 from '@angular/router/src/directives/router_link';
import * as import40 from '@angular/router/src/directives/router_link_active';
export class Wrapper_UserProfileComponent {
  /*private*/ _eventHandler:Function;
  context:import0.UserProfileComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.UserProfileComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_UserProfileComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_UserProfileComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.UserProfileComponent>;
  _UserProfileComponent_0_3:Wrapper_UserProfileComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UserProfileComponent_Host0,renderType_UserProfileComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-user-profile',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_UserProfileComponent0(this.viewUtils,this,0,this._el_0);
    this._UserProfileComponent_0_3 = new Wrapper_UserProfileComponent(this.injectorGet(import8.Store,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex),this.injectorGet(import10.CloudinaryIntegrationService,this.parentIndex),this.injectorGet(import11.UserService,this.parentIndex));
    this.compView_0.create(this._UserProfileComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._UserProfileComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.UserProfileComponent) && (0 === requestNodeIndex))) { return this._UserProfileComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UserProfileComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._UserProfileComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const UserProfileComponentNgFactory:import7.ComponentFactory<import0.UserProfileComponent> = new import7.ComponentFactory<import0.UserProfileComponent>('tr-user-profile',View_UserProfileComponent_Host0,import0.UserProfileComponent);
const styles_UserProfileComponent:any[] = [import12.styles];
var UserProfileComponent_flyInDown_states:any = {
  'in': {},
  '*': {},
  'void': {}
}
;
function UserProfileComponent_flyInDown_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import13.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'flyInDown'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = UserProfileComponent_flyInDown_states['*'];
  var startStateStyles:any = UserProfileComponent_flyInDown_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = UserProfileComponent_flyInDown_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'top': '-5%',
          'opacity': '0'
        }

      ]
      )),import16.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,(null as any),previousPlayers)]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import18.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import16.renderStyles(element,view.renderer,import16.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import14.AnimationSequencePlayer(previousPlayers).destroy();
  import16.renderStyles(element,view.renderer,import16.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'flyInDown',player);
  return new import13.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_UserProfileComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent1,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray2(2,'class','ui centered image profile-image'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = ((this.parentView.context.selectedUser.profile_pic == null)? (null as any): this.parentView.context.selectedUser.profile_pic.url);
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_UserProfileComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent2,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray2(2,'class','ui centered image profile-image'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.profilePicSrc;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_UserProfileComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent3,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','update-icon-text'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n						',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray2(2,'class','big photo icon'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_UserProfileComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent4,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_7 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','follow'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','ui facebook button'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n					',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'i',new import3.InlineArray2(2,'class','plus icon'),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n			',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7:any = import3.inlineInterpolate(1,'\n					',((this.parentView.context.userFollowState() == 'inactive')? 'Follow': 'Following'),'\n				');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_5,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onToggleFollow()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_UserProfileComponent5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent5,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray2(2,'class','cover-image'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = ((this.parentView.context.selectedUser.cover_photo == null)? (null as any): this.parentView.context.selectedUser.cover_photo.url);
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_UserProfileComponent6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent6,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray2(2,'class','cover-image'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.coverPhotoSrc;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_UserProfileComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_UserProfileComponent7,renderType_UserProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','cover-update-text'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray2(2,'class','big photo icon'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','cover-photo-update-text1'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Update Cover',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','cover-photo-update-text2'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Photo',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n		',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onUpdateCoverPhoto()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_UserProfileComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_UserProfileComponent,{flyInDown: UserProfileComponent_flyInDown_factory});
export class View_UserProfileComponent0 extends import1.AppView<import0.UserProfileComponent> {
  _el_0:any;
  /*private*/ _vc_0:import19.ViewContainer;
  _RouterOutlet_0_5:import22.Wrapper_RouterOutlet;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _NgClass_10_3:import23.Wrapper_NgClass;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import19.ViewContainer;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import24.Wrapper_NgIf;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import19.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import24.Wrapper_NgIf;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import19.ViewContainer;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import24.Wrapper_NgIf;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _vc_26:import19.ViewContainer;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import24.Wrapper_NgIf;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _vc_34:import19.ViewContainer;
  _TemplateRef_34_5:any;
  _NgIf_34_6:import24.Wrapper_NgIf;
  _text_35:any;
  _anchor_36:any;
  /*private*/ _vc_36:import19.ViewContainer;
  _TemplateRef_36_5:any;
  _NgIf_36_6:import24.Wrapper_NgIf;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _vc_38:import19.ViewContainer;
  _TemplateRef_38_5:any;
  _NgIf_38_6:import24.Wrapper_NgIf;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _RouterLink_43_3:import25.Wrapper_RouterLink;
  _RouterLinkActive_43_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_43_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_43_1:import27.QueryList<any>;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _RouterLink_46_3:import25.Wrapper_RouterLink;
  _RouterLinkActive_46_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_46_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_46_1:import27.QueryList<any>;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _RouterLink_49_3:import25.Wrapper_RouterLink;
  _RouterLinkActive_49_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_49_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_49_1:import27.QueryList<any>;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _RouterLink_52_3:import25.Wrapper_RouterLink;
  _RouterLinkActive_52_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_52_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_52_1:import27.QueryList<any>;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  /*private*/ _vc_63:import19.ViewContainer;
  _RouterOutlet_63_5:import22.Wrapper_RouterOutlet;
  _text_64:any;
  _text_65:any;
  /*private*/ _expr_108:any;
  _pipe_async_0:import28.AsyncPipe;
  _map_110:any;
  _pipe_async_1:import28.AsyncPipe;
  /*private*/ _expr_112:any;
  _pipe_async_2:import28.AsyncPipe;
  /*private*/ _expr_114:any;
  _pipe_async_3:import28.AsyncPipe;
  _arr_116:any;
  _arr_117:any;
  _arr_118:any;
  _arr_119:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UserProfileComponent0,renderType_UserProfileComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_108 = import20.UNINITIALIZED;
    this._map_110 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {'logged-in-user': p0};
    });
    this._expr_112 = import20.UNINITIALIZED;
    this._expr_114 = import20.UNINITIALIZED;
    this._arr_116 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_117 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_118 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_119 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_0 = new import19.ViewContainer(0,(null as any),this,this._el_0);
    this._RouterOutlet_0_5 = new import22.Wrapper_RouterOutlet(this.parentView.injectorGet(import29.RouterOutletMap,this.parentIndex),this._vc_0.vcRef,this.parentView.injectorGet(import30.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','profile-cover'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','image profile-cover-div'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','profile-info'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','profile-image-div text-white'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n				',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','profile-image-text'),(null as any));
    this._NgClass_10_3 = new import23.Wrapper_NgClass(this.parentView.injectorGet(import31.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import32.KeyValueDiffers,this.parentIndex),new import33.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText(this._el_10,'\n					',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import19.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import34.TemplateRef_(this,12,this._anchor_12);
    this._NgIf_12_6 = new import24.Wrapper_NgIf(this._vc_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n					',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_14 = new import19.ViewContainer(14,10,this,this._anchor_14);
    this._TemplateRef_14_5 = new import34.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import24.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_10,'\n					',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_16 = new import19.ViewContainer(16,10,this,this._anchor_16);
    this._TemplateRef_16_5 = new import34.TemplateRef_(this,16,this._anchor_16);
    this._NgIf_16_6 = new import24.Wrapper_NgIf(this._vc_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_10,'\n				',(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n				',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_8,'h1',new import3.InlineArray2(2,'class','profile-name'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_8,'\n				',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_8,'h4',new import3.InlineArray2(2,'class','profile-bio'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Designer and Developer living Pune, IN',(null as any));
    this._text_24 = this.renderer.createText(this._el_8,'\n			',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_26 = new import19.ViewContainer(26,6,this,this._anchor_26);
    this._TemplateRef_26_5 = new import34.TemplateRef_(this,26,this._anchor_26);
    this._NgIf_26_6 = new import24.Wrapper_NgIf(this._vc_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n				',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'input',new import3.InlineArray8(8,'accept','image/*','id','selectMedia','name','file','type','file'),(null as any));
    this._text_31 = this.renderer.createText(this._el_28,'\n			',(null as any));
    this._text_32 = this.renderer.createText(this._el_6,'\n		',(null as any));
    this._text_33 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_34 = new import19.ViewContainer(34,4,this,this._anchor_34);
    this._TemplateRef_34_5 = new import34.TemplateRef_(this,34,this._anchor_34);
    this._NgIf_34_6 = new import24.Wrapper_NgIf(this._vc_34.vcRef,this._TemplateRef_34_5);
    this._text_35 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._anchor_36 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_36 = new import19.ViewContainer(36,4,this,this._anchor_36);
    this._TemplateRef_36_5 = new import34.TemplateRef_(this,36,this._anchor_36);
    this._NgIf_36_6 = new import24.Wrapper_NgIf(this._vc_36.vcRef,this._TemplateRef_36_5);
    this._text_37 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_38 = new import19.ViewContainer(38,4,this,this._anchor_38);
    this._TemplateRef_38_5 = new import34.TemplateRef_(this,38,this._anchor_38);
    this._NgIf_38_6 = new import24.Wrapper_NgIf(this._vc_38.vcRef,this._TemplateRef_38_5);
    this._text_39 = this.renderer.createText(this._el_4,'\n	',(null as any));
    this._text_40 = this.renderer.createText(this._el_2,'\n\n	',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','ui grid centered profile-nav'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n		',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'span',new import3.InlineArray4(4,'class','profile-nav-links','routerLinkActive','active'),(null as any));
    this._RouterLink_43_3 = new import25.Wrapper_RouterLink(this.parentView.injectorGet(import35.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_43_4 = new import26.Wrapper_RouterLinkActive(this.parentView.injectorGet(import35.Router,this.parentIndex),new import33.ElementRef(this._el_43),this.renderer);
    this._query_RouterLink_43_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_43_1 = new import27.QueryList<any>();
    this._text_44 = this.renderer.createText(this._el_43,'Trips',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,'\n		',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_41,'span',new import3.InlineArray4(4,'class','profile-nav-links','routerLinkActive','active'),(null as any));
    this._RouterLink_46_3 = new import25.Wrapper_RouterLink(this.parentView.injectorGet(import35.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_46_4 = new import26.Wrapper_RouterLinkActive(this.parentView.injectorGet(import35.Router,this.parentIndex),new import33.ElementRef(this._el_46),this.renderer);
    this._query_RouterLink_46_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_46_1 = new import27.QueryList<any>();
    this._text_47 = this.renderer.createText(this._el_46,'Followers',(null as any));
    this._text_48 = this.renderer.createText(this._el_41,'\n		',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_41,'span',new import3.InlineArray4(4,'class','profile-nav-links','routerLinkActive','active'),(null as any));
    this._RouterLink_49_3 = new import25.Wrapper_RouterLink(this.parentView.injectorGet(import35.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_49_4 = new import26.Wrapper_RouterLinkActive(this.parentView.injectorGet(import35.Router,this.parentIndex),new import33.ElementRef(this._el_49),this.renderer);
    this._query_RouterLink_49_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_49_1 = new import27.QueryList<any>();
    this._text_50 = this.renderer.createText(this._el_49,'Following',(null as any));
    this._text_51 = this.renderer.createText(this._el_41,'\n		',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_41,'span',new import3.InlineArray4(4,'class','profile-nav-links','routerLinkActive','active'),(null as any));
    this._RouterLink_52_3 = new import25.Wrapper_RouterLink(this.parentView.injectorGet(import35.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_52_4 = new import26.Wrapper_RouterLinkActive(this.parentView.injectorGet(import35.Router,this.parentIndex),new import33.ElementRef(this._el_52),this.renderer);
    this._query_RouterLink_52_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_52_1 = new import27.QueryList<any>();
    this._text_53 = this.renderer.createText(this._el_52,'Media',(null as any));
    this._text_54 = this.renderer.createText(this._el_41,'\n	',(null as any));
    this._text_55 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_56 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','main ui grid'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n	',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_57,'div',new import3.InlineArray2(2,'class','four wide column'),(null as any));
    this._text_60 = this.renderer.createText(this._el_57,'\n	',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_57,'div',new import3.InlineArray2(2,'class','eight wide column'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n		',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_63 = new import19.ViewContainer(63,61,this,this._el_63);
    this._RouterOutlet_63_5 = new import22.Wrapper_RouterOutlet(this.parentView.injectorGet(import29.RouterOutletMap,this.parentIndex),this._vc_63.vcRef,this.parentView.injectorGet(import30.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_64 = this.renderer.createText(this._el_61,'\n	',(null as any));
    this._text_65 = this.renderer.createText(this._el_57,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    this._pipe_async_0 = new import28.AsyncPipe(this.ref);
    this._pipe_async_1 = new import28.AsyncPipe(this.ref);
    this._pipe_async_2 = new import28.AsyncPipe(this.ref);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_30));
    this._pipe_async_3 = new import28.AsyncPipe(this.ref);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_43,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_43));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_46,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_46));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_49,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_49));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_52,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_52));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._anchor_36,
      this._text_37,
      this._anchor_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.RouterOutlet) && (0 === requestNodeIndex))) { return this._RouterOutlet_0_5.context; }
    if (((token === import34.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import37.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import34.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import37.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import34.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import37.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import38.NgClass) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgClass_10_3.context; }
    if (((token === import34.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import37.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    if (((token === import34.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import37.NgIf) && (34 === requestNodeIndex))) { return this._NgIf_34_6.context; }
    if (((token === import34.TemplateRef) && (36 === requestNodeIndex))) { return this._TemplateRef_36_5; }
    if (((token === import37.NgIf) && (36 === requestNodeIndex))) { return this._NgIf_36_6.context; }
    if (((token === import34.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import37.NgIf) && (38 === requestNodeIndex))) { return this._NgIf_38_6.context; }
    if (((token === import39.RouterLink) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._RouterLink_43_3.context; }
    if (((token === import40.RouterLinkActive) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._RouterLinkActive_43_4.context; }
    if (((token === import39.RouterLink) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._RouterLink_46_3.context; }
    if (((token === import40.RouterLinkActive) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._RouterLinkActive_46_4.context; }
    if (((token === import39.RouterLink) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._RouterLink_49_3.context; }
    if (((token === import40.RouterLinkActive) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._RouterLinkActive_49_4.context; }
    if (((token === import39.RouterLink) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._RouterLink_52_3.context; }
    if (((token === import40.RouterLinkActive) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._RouterLinkActive_52_4.context; }
    if (((token === import36.RouterOutlet) && (63 === requestNodeIndex))) { return this._RouterOutlet_63_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import20.ValueUnwrapper();
    const currVal_108:any = 'in';
    if (import3.checkBinding(throwOnChange,this._expr_108,currVal_108)) {
      var animationTransition_flyInDown:any = this.componentType.animations['flyInDown'](this,this._el_6,((this._expr_108 == import20.UNINITIALIZED)? 'void': this._expr_108),((currVal_108 == import20.UNINITIALIZED)? 'void': currVal_108));
      this._expr_108 = currVal_108;
    }
    this._RouterOutlet_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_10_0_0:any = 'profile-image-text';
    this._NgClass_10_3.check_klass(currVal_10_0_0,throwOnChange,false);
    valUnwrapper.reset();
    const currVal_10_0_1:any = this._map_110((valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.loggedUserId$)) == this.context.userIndex));
    this._NgClass_10_3.check_ngClass(currVal_10_0_1,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgClass_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_12_0_0:boolean = !this.context.profilePicSrc;
    this._NgIf_12_6.check_ngIf(currVal_12_0_0,throwOnChange,false);
    this._NgIf_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_14_0_0:any = this.context.profilePicSrc;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    valUnwrapper.reset();
    const currVal_16_0_0:any = (valUnwrapper.unwrap(this._pipe_async_1.transform(this.context.loggedUserId$)) == this.context.userIndex);
    this._NgIf_16_6.check_ngIf(currVal_16_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    valUnwrapper.reset();
    const currVal_26_0_0:any = (valUnwrapper.unwrap(this._pipe_async_2.transform(this.context.loggedUserId$)) != this.context.userIndex);
    this._NgIf_26_6.check_ngIf(currVal_26_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_26_6.ngDoCheck(this,this._anchor_26,throwOnChange);
    const currVal_34_0_0:boolean = !this.context.coverPhotoSrc;
    this._NgIf_34_6.check_ngIf(currVal_34_0_0,throwOnChange,false);
    this._NgIf_34_6.ngDoCheck(this,this._anchor_34,throwOnChange);
    const currVal_36_0_0:any = this.context.coverPhotoSrc;
    this._NgIf_36_6.check_ngIf(currVal_36_0_0,throwOnChange,false);
    this._NgIf_36_6.ngDoCheck(this,this._anchor_36,throwOnChange);
    valUnwrapper.reset();
    const currVal_38_0_0:any = (valUnwrapper.unwrap(this._pipe_async_3.transform(this.context.loggedUserId$)) == this.context.userIndex);
    this._NgIf_38_6.check_ngIf(currVal_38_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_38_6.ngDoCheck(this,this._anchor_38,throwOnChange);
    const currVal_43_0_0:any = this._arr_116('trips');
    this._RouterLink_43_3.check_routerLink(currVal_43_0_0,throwOnChange,false);
    this._RouterLink_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_1_0:any = 'active';
    this._RouterLinkActive_43_4.check_routerLinkActive(currVal_43_1_0,throwOnChange,false);
    this._RouterLinkActive_43_4.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_46_0_0:any = this._arr_117('followers');
    this._RouterLink_46_3.check_routerLink(currVal_46_0_0,throwOnChange,false);
    this._RouterLink_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_46_1_0:any = 'active';
    this._RouterLinkActive_46_4.check_routerLinkActive(currVal_46_1_0,throwOnChange,false);
    this._RouterLinkActive_46_4.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_49_0_0:any = this._arr_118('following');
    this._RouterLink_49_3.check_routerLink(currVal_49_0_0,throwOnChange,false);
    this._RouterLink_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_1_0:any = 'active';
    this._RouterLinkActive_49_4.check_routerLinkActive(currVal_49_1_0,throwOnChange,false);
    this._RouterLinkActive_49_4.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_52_0_0:any = this._arr_119('media');
    this._RouterLink_52_3.check_routerLink(currVal_52_0_0,throwOnChange,false);
    this._RouterLink_52_3.ngDoCheck(this,this._el_52,throwOnChange);
    const currVal_52_1_0:any = 'active';
    this._RouterLinkActive_52_4.check_routerLinkActive(currVal_52_1_0,throwOnChange,false);
    this._RouterLinkActive_52_4.ngDoCheck(this,this._el_52,throwOnChange);
    this._RouterOutlet_63_5.ngDoCheck(this,this._el_63,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    this._vc_34.detectChangesInNestedViews(throwOnChange);
    this._vc_36.detectChangesInNestedViews(throwOnChange);
    this._vc_38.detectChangesInNestedViews(throwOnChange);
    this._vc_63.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_43_0.dirty) {
        this._query_RouterLink_43_0.reset([this._RouterLink_43_3.context]);
        this._RouterLinkActive_43_4.context.links = this._query_RouterLink_43_0;
        this._query_RouterLink_43_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_43_1.dirty) {
        this._query_RouterLinkWithHref_43_1.reset(([] as any[]));
        this._RouterLinkActive_43_4.context.linksWithHrefs = this._query_RouterLinkWithHref_43_1;
        this._query_RouterLinkWithHref_43_1.notifyOnChanges();
      }
      if (this._query_RouterLink_46_0.dirty) {
        this._query_RouterLink_46_0.reset([this._RouterLink_46_3.context]);
        this._RouterLinkActive_46_4.context.links = this._query_RouterLink_46_0;
        this._query_RouterLink_46_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_46_1.dirty) {
        this._query_RouterLinkWithHref_46_1.reset(([] as any[]));
        this._RouterLinkActive_46_4.context.linksWithHrefs = this._query_RouterLinkWithHref_46_1;
        this._query_RouterLinkWithHref_46_1.notifyOnChanges();
      }
      if (this._query_RouterLink_49_0.dirty) {
        this._query_RouterLink_49_0.reset([this._RouterLink_49_3.context]);
        this._RouterLinkActive_49_4.context.links = this._query_RouterLink_49_0;
        this._query_RouterLink_49_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_49_1.dirty) {
        this._query_RouterLinkWithHref_49_1.reset(([] as any[]));
        this._RouterLinkActive_49_4.context.linksWithHrefs = this._query_RouterLinkWithHref_49_1;
        this._query_RouterLinkWithHref_49_1.notifyOnChanges();
      }
      if (this._query_RouterLink_52_0.dirty) {
        this._query_RouterLink_52_0.reset([this._RouterLink_52_3.context]);
        this._RouterLinkActive_52_4.context.links = this._query_RouterLink_52_0;
        this._query_RouterLink_52_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_52_1.dirty) {
        this._query_RouterLinkWithHref_52_1.reset(([] as any[]));
        this._RouterLinkActive_52_4.context.linksWithHrefs = this._query_RouterLinkWithHref_52_1;
        this._query_RouterLinkWithHref_52_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_43_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_46_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_49_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_52_4.context.ngAfterContentInit(); }
    }
    const currVal_112:any = import3.inlineInterpolate(1,'',this.context.selectedUser.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_112,currVal_112)) {
      this.renderer.setText(this._text_20,currVal_112);
      this._expr_112 = currVal_112;
    }
    const currVal_114:any = true;
    if (import3.checkBinding(throwOnChange,this._expr_114,currVal_114)) {
      this.renderer.setElementProperty(this._el_28,'hidden',currVal_114);
      this._expr_114 = currVal_114;
    }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this._vc_12.destroyNestedViews();
    this._vc_14.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_26.destroyNestedViews();
    this._vc_34.destroyNestedViews();
    this._vc_36.destroyNestedViews();
    this._vc_38.destroyNestedViews();
    this._vc_63.destroyNestedViews();
    this._RouterOutlet_0_5.ngOnDestroy();
    this._RouterLinkActive_43_4.ngOnDestroy();
    this._RouterLinkActive_46_4.ngOnDestroy();
    this._RouterLinkActive_49_4.ngOnDestroy();
    this._RouterLinkActive_52_4.ngOnDestroy();
    this._RouterOutlet_63_5.ngOnDestroy();
    this._pipe_async_0.ngOnDestroy();
    this._pipe_async_1.ngOnDestroy();
    this._pipe_async_2.ngOnDestroy();
    this._pipe_async_3.ngOnDestroy();
  }
  detachInternal():void {
    var animationTransition_flyInDown:any = this.componentType.animations['flyInDown'](this,this._el_6,this._expr_108,'void');
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_UserProfileComponent1(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 14)) { return new View_UserProfileComponent2(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 16)) { return new View_UserProfileComponent3(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 26)) { return new View_UserProfileComponent4(this.viewUtils,this,26,this._anchor_26,this._vc_26); }
    if ((nodeIndex == 34)) { return new View_UserProfileComponent5(this.viewUtils,this,34,this._anchor_34,this._vc_34); }
    if ((nodeIndex == 36)) { return new View_UserProfileComponent6(this.viewUtils,this,36,this._anchor_36,this._vc_36); }
    if ((nodeIndex == 38)) { return new View_UserProfileComponent7(this.viewUtils,this,38,this._anchor_38,this._vc_38); }
    return (null as any);
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onUpdateProfilePicture()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.handleInputChange($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_43(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_43_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_46(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_46_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_49(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_49_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_52(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_52_3.handleEvent(eventName,$event) && result);
    return result;
  }
}