/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../src/app/components/shared/auth/login/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/forms/src/form_builder';
import * as import9 from '@ngrx/store/src/store';
import * as import10 from '@angular/router/src/router';
import * as import11 from 'ng2-toasty/src/toasty.service';
import * as import12 from './login.component.scss.shim.ngstyle';
import * as import13 from '../../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import14 from '../../../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import17 from '../../../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import27 from '@angular/forms/src/directives/control_container';
import * as import28 from '@angular/router/src/directives/router_link';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _LoginComponent_0_3:Wrapper_LoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-login',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._LoginComponent_0_3 = new Wrapper_LoginComponent(this.injectorGet(import8.FormBuilder,this.parentIndex),this.injectorGet(import9.Store,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex),this.injectorGet(import11.ToastyService,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import7.ComponentFactory<import0.LoginComponent> = new import7.ComponentFactory<import0.LoginComponent>('tr-login',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = [import12.styles];
var renderType_LoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _FormGroupDirective_14_3:import13.Wrapper_FormGroupDirective;
  _ControlContainer_14_4:any;
  _NgControlStatusGroup_14_5:import14.Wrapper_NgControlStatusGroup;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _DefaultValueAccessor_24_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_24_4:any[];
  _FormControlName_24_5:import16.Wrapper_FormControlName;
  _NgControl_24_6:any;
  _NgControlStatus_24_7:import14.Wrapper_NgControlStatus;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _FormControlName_34_5:import16.Wrapper_FormControlName;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import14.Wrapper_NgControlStatus;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _RouterLinkWithHref_45_3:import17.Wrapper_RouterLinkWithHref;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _arr_64:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_64 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','ui middle aligned center aligned grid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','sixteen wide column'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','sixteen wide column'),(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','five wide column'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h2',new import3.InlineArray2(2,'class','ui teal image header'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        Log-in\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'form',new import3.InlineArray2(2,'class','ui medium form'),(null as any));
    this._FormGroupDirective_14_3 = new import13.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_14_4 = this._FormGroupDirective_14_3.context;
    this._NgControlStatusGroup_14_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_14_4);
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','ui stacked segment'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','field'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','ui left icon input'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'i',new import3.InlineArray2(2,'class','user icon'),(null as any));
    this._text_23 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_20,'input',new import3.InlineArray16(10,'autocomplete','off','formControlName','email','name','email','placeholder','E-mail address','type','text'),(null as any));
    this._DefaultValueAccessor_24_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_24));
    this._NG_VALUE_ACCESSOR_24_4 = [this._DefaultValueAccessor_24_3.context];
    this._FormControlName_24_5 = new import16.Wrapper_FormControlName(this._ControlContainer_14_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_24_4);
    this._NgControl_24_6 = this._FormControlName_24_5.context;
    this._NgControlStatus_24_7 = new import14.Wrapper_NgControlStatus(this._NgControl_24_6);
    this._text_25 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._text_26 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','field'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n          ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','ui left icon input'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'i',new import3.InlineArray2(2,'class','lock icon'),(null as any));
    this._text_33 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_30,'input',new import3.InlineArray16(10,'autocomplete','off','formControlName','password','name','password','placeholder','Password','type','password'),(null as any));
    this._DefaultValueAccessor_34_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3.context];
    this._FormControlName_34_5 = new import16.Wrapper_FormControlName(this._ControlContainer_14_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._FormControlName_34_5.context;
    this._NgControlStatus_34_7 = new import14.Wrapper_NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._text_36 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_16,'button',new import3.InlineArray4(4,'class','ui fluid large teal submit button','type','submit'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Sign in',(null as any));
    this._text_40 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_14,'\n\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_6,'\n\n    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','ui message'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n      New to Yatrum? ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_45_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import19.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import20.LocationStrategy,this.parentIndex));
    this._text_46 = this.renderer.createText(this._el_45,'Sign Up',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_49 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_14));
    this._FormGroupDirective_14_3.subscribe(this,this.eventHandler(this.handleEvent_14),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_34));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_45));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.DefaultValueAccessor) && (24 === requestNodeIndex))) { return this._DefaultValueAccessor_24_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (24 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_24_4; }
    if (((token === import23.FormControlName) && (24 === requestNodeIndex))) { return this._FormControlName_24_5.context; }
    if (((token === import24.NgControl) && (24 === requestNodeIndex))) { return this._NgControl_24_6; }
    if (((token === import25.NgControlStatus) && (24 === requestNodeIndex))) { return this._NgControlStatus_24_7.context; }
    if (((token === import21.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import23.FormControlName) && (34 === requestNodeIndex))) { return this._FormControlName_34_5.context; }
    if (((token === import24.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import25.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7.context; }
    if (((token === import26.FormGroupDirective) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._FormGroupDirective_14_3.context; }
    if (((token === import27.ControlContainer) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ControlContainer_14_4; }
    if (((token === import25.NgControlStatusGroup) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgControlStatusGroup_14_5.context; }
    if (((token === import28.RouterLinkWithHref) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._RouterLinkWithHref_45_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_14_0_0:any = this.context.signInForm;
    this._FormGroupDirective_14_3.check_form(currVal_14_0_0,throwOnChange,false);
    this._FormGroupDirective_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this._NgControlStatusGroup_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    this._DefaultValueAccessor_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    const currVal_24_1_0:any = 'email';
    this._FormControlName_24_5.check_name(currVal_24_1_0,throwOnChange,false);
    this._FormControlName_24_5.ngDoCheck(this,this._el_24,throwOnChange);
    this._NgControlStatus_24_7.ngDoCheck(this,this._el_24,throwOnChange);
    this._DefaultValueAccessor_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_34_1_0:any = 'password';
    this._FormControlName_34_5.check_name(currVal_34_1_0,throwOnChange,false);
    this._FormControlName_34_5.ngDoCheck(this,this._el_34,throwOnChange);
    this._NgControlStatus_34_7.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_45_0_0:any = this._arr_64('/signup');
    this._RouterLinkWithHref_45_3.check_routerLink(currVal_45_0_0,throwOnChange,false);
    this._RouterLinkWithHref_45_3.ngDoCheck(this,this._el_45,throwOnChange);
    this._NgControlStatusGroup_14_5.checkHost(this,this,this._el_14,throwOnChange);
    this._NgControlStatus_24_7.checkHost(this,this,this._el_24,throwOnChange);
    this._NgControlStatus_34_7.checkHost(this,this,this._el_34,throwOnChange);
    this._RouterLinkWithHref_45_3.checkHost(this,this,this._el_45,throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_24_5.ngOnDestroy();
    this._FormControlName_34_5.ngOnDestroy();
    this._FormGroupDirective_14_3.ngOnDestroy();
    this._RouterLinkWithHref_45_3.ngOnDestroy();
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_24_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_34_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_45_3.handleEvent(eventName,$event) && result);
    return result;
  }
}