/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../src/app/components/trips/trip-detail/new-trip-comment/new-trip-comment.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@ngrx/store/src/store';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from './new-trip-comment.component.scss.shim.ngstyle';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import14 from '../../../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import17 from '../../../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
import * as import25 from '@angular/common/src/directives/ng_if';
import * as import26 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import27 from '@angular/forms/src/directives/control_container';
import * as import28 from '@angular/core/src/security';
import * as import29 from '@angular/common/src/pipes/async_pipe';
export class Wrapper_NewTripCommentComponent {
  /*private*/ _eventHandler:Function;
  context:import0.NewTripCommentComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.NewTripCommentComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_trip(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.trip = currValue;
      this._expr_0 = currValue;
    }
  }
  check_authUser(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.authUser = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_NewTripCommentComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_NewTripCommentComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.NewTripCommentComponent>;
  _NewTripCommentComponent_0_3:Wrapper_NewTripCommentComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NewTripCommentComponent_Host0,renderType_NewTripCommentComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'tr-new-trip-comment',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_NewTripCommentComponent0(this.viewUtils,this,0,this._el_0);
    this._NewTripCommentComponent_0_3 = new Wrapper_NewTripCommentComponent(this.injectorGet(import9.Store,this.parentIndex),this.injectorGet(import10.FormBuilder,this.parentIndex));
    this.compView_0.create(this._NewTripCommentComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._NewTripCommentComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NewTripCommentComponent) && (0 === requestNodeIndex))) { return this._NewTripCommentComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._NewTripCommentComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const NewTripCommentComponentNgFactory:import8.ComponentFactory<import0.NewTripCommentComponent> = new import8.ComponentFactory<import0.NewTripCommentComponent>('tr-new-trip-comment',View_NewTripCommentComponent_Host0,import0.NewTripCommentComponent);
const styles_NewTripCommentComponent:any[] = [import11.styles];
class View_NewTripCommentComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_NewTripCommentComponent2,renderType_NewTripCommentComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','ui basic green button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Send',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.onCommentSave()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_NewTripCommentComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_NewTripCommentComponent3,renderType_NewTripCommentComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','ui basic red button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Cancel',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.onCancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_NewTripCommentComponent1 extends import2.AppView<any> {
  _el_0:any;
  _FormGroupDirective_0_3:import13.Wrapper_FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import14.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _DefaultValueAccessor_14_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_14_4:any[];
  _FormControlName_14_5:import16.Wrapper_FormControlName;
  _NgControl_14_6:any;
  _NgControlStatus_14_7:import14.Wrapper_NgControlStatus;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_17_4:any[];
  _FormControlName_17_5:import16.Wrapper_FormControlName;
  _NgControl_17_6:any;
  _NgControlStatus_17_7:import14.Wrapper_NgControlStatus;
  _text_18:any;
  _el_19:any;
  _DefaultValueAccessor_19_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_19_4:any[];
  _FormControlName_19_5:import16.Wrapper_FormControlName;
  _NgControl_19_6:any;
  _NgControlStatus_19_7:import14.Wrapper_NgControlStatus;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import12.ViewContainer;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import17.Wrapper_NgIf;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import12.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import17.Wrapper_NgIf;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_NewTripCommentComponent1,renderType_NewTripCommentComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_57 = import1.UNINITIALIZED;
    this._expr_58 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'form',new import3.InlineArray2(2,'class','card sixteen wide column'),(null as any));
    this._FormGroupDirective_0_3 = new import13.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3.context;
    this._NgControlStatusGroup_0_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'img',new import3.InlineArray4(4,'aria-hidden','true','class','right floated mini ui image'),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','meta'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','description'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'textarea',new import3.InlineArray16(10,'class','input-group-field','formControlName','message','id','message','placeholder','Add Comment','type','text'),(null as any));
    this._DefaultValueAccessor_14_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_14));
    this._NG_VALUE_ACCESSOR_14_4 = [this._DefaultValueAccessor_14_3.context];
    this._FormControlName_14_5 = new import16.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_14_4);
    this._NgControl_14_6 = this._FormControlName_14_5.context;
    this._NgControlStatus_14_7 = new import14.Wrapper_NgControlStatus(this._NgControl_14_6);
    this._text_15 = this.renderer.createText(this._el_14,'      ',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_12,'input',new import3.InlineArray4(4,'formControlName','user_id','type','hidden'),(null as any));
    this._DefaultValueAccessor_17_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_17));
    this._NG_VALUE_ACCESSOR_17_4 = [this._DefaultValueAccessor_17_3.context];
    this._FormControlName_17_5 = new import16.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_17_4);
    this._NgControl_17_6 = this._FormControlName_17_5.context;
    this._NgControlStatus_17_7 = new import14.Wrapper_NgControlStatus(this._NgControl_17_6);
    this._text_18 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_12,'input',new import3.InlineArray4(4,'formControlName','trip_id','type','hidden'),(null as any));
    this._DefaultValueAccessor_19_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_19));
    this._NG_VALUE_ACCESSOR_19_4 = [this._DefaultValueAccessor_19_3.context];
    this._FormControlName_19_5 = new import16.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_19_4);
    this._NgControl_19_6 = this._FormControlName_19_5.context;
    this._NgControlStatus_19_7 = new import14.Wrapper_NgControlStatus(this._NgControl_19_6);
    this._text_20 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','extra content ui grid'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'div',new import3.InlineArray2(2,'class','ui five buttons wide right aligned column'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import12.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import19.TemplateRef_(this,27,this._anchor_27);
    this._NgIf_27_6 = new import17.Wrapper_NgIf(this._vc_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_29 = new import12.ViewContainer(29,25,this,this._anchor_29);
    this._TemplateRef_29_5 = new import19.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import17.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_23,'\n  ',(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    this._FormGroupDirective_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray8(6,'keypress',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_19));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31,
      this._text_32
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DefaultValueAccessor) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._DefaultValueAccessor_14_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._NG_VALUE_ACCESSOR_14_4; }
    if (((token === import22.FormControlName) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._FormControlName_14_5.context; }
    if (((token === import23.NgControl) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._NgControl_14_6; }
    if (((token === import24.NgControlStatus) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._NgControlStatus_14_7.context; }
    if (((token === import20.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_4; }
    if (((token === import22.FormControlName) && (17 === requestNodeIndex))) { return this._FormControlName_17_5.context; }
    if (((token === import23.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_6; }
    if (((token === import24.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_7.context; }
    if (((token === import20.DefaultValueAccessor) && (19 === requestNodeIndex))) { return this._DefaultValueAccessor_19_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (19 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_19_4; }
    if (((token === import22.FormControlName) && (19 === requestNodeIndex))) { return this._FormControlName_19_5.context; }
    if (((token === import23.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_6; }
    if (((token === import24.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_7.context; }
    if (((token === import19.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import25.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    if (((token === import19.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import25.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    if (((token === import26.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._FormGroupDirective_0_3.context; }
    if (((token === import27.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ControlContainer_0_4; }
    if (((token === import24.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.commentForm;
    this._FormGroupDirective_0_3.check_form(currVal_0_0_0,throwOnChange,false);
    this._FormGroupDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._DefaultValueAccessor_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_14_1_0:any = 'message';
    this._FormControlName_14_5.check_name(currVal_14_1_0,throwOnChange,false);
    this._FormControlName_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    this._NgControlStatus_14_7.ngDoCheck(this,this._el_14,throwOnChange);
    this._DefaultValueAccessor_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_1_0:any = 'user_id';
    this._FormControlName_17_5.check_name(currVal_17_1_0,throwOnChange,false);
    const currVal_17_1_1:any = ((this.parentView.context.authUser == null)? (null as any): this.parentView.context.authUser.id);
    this._FormControlName_17_5.check_model(currVal_17_1_1,throwOnChange,false);
    this._FormControlName_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatus_17_7.ngDoCheck(this,this._el_17,throwOnChange);
    this._DefaultValueAccessor_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_19_1_0:any = 'trip_id';
    this._FormControlName_19_5.check_name(currVal_19_1_0,throwOnChange,false);
    const currVal_19_1_1:any = ((this.parentView.context.trip == null)? (null as any): this.parentView.context.trip.id);
    this._FormControlName_19_5.check_model(currVal_19_1_1,throwOnChange,false);
    this._FormControlName_19_5.ngDoCheck(this,this._el_19,throwOnChange);
    this._NgControlStatus_19_7.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_27_0_0:any = this.parentView.context.commentForm.valid;
    this._NgIf_27_6.check_ngIf(currVal_27_0_0,throwOnChange,false);
    this._NgIf_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    const currVal_29_0_0:any = this.parentView.context.commentForm.valid;
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    const currVal_57:any = this.parentView.context.authUser.profile_pic.url;
    if (import3.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_57));
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = import3.inlineInterpolate(1,'\n      ',this.parentView.context.authUser.name,'\n    ');
    if (import3.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setText(this._text_7,currVal_58);
      this._expr_58 = currVal_58;
    }
    this._NgControlStatus_14_7.checkHost(this,this,this._el_14,throwOnChange);
    this._NgControlStatus_17_7.checkHost(this,this,this._el_17,throwOnChange);
    this._NgControlStatus_19_7.checkHost(this,this,this._el_19,throwOnChange);
  }
  destroyInternal():void {
    this._vc_27.destroyNestedViews();
    this._vc_29.destroyNestedViews();
    this._FormControlName_14_5.ngOnDestroy();
    this._FormControlName_17_5.ngOnDestroy();
    this._FormControlName_19_5.ngOnDestroy();
    this._FormGroupDirective_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 27)) { return new View_NewTripCommentComponent2(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    if ((nodeIndex == 29)) { return new View_NewTripCommentComponent3(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onCommentSave()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'keypress')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onKeyPressed($event.keyCode)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_17_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_NewTripCommentComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_NewTripCommentComponent,{});
export class View_NewTripCommentComponent0 extends import2.AppView<import0.NewTripCommentComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import12.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import17.Wrapper_NgIf;
  _pipe_async_0:import29.AsyncPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NewTripCommentComponent0,renderType_NewTripCommentComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import12.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import19.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import17.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._pipe_async_0 = new import29.AsyncPipe(this.ref);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._anchor_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import25.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_0_0_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.userIsAuthenticated));
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this._pipe_async_0.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_NewTripCommentComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}